"use client";

import React, { use } from "react";
import { FileText, Settings, ShieldCheck, Database } from "lucide-react";
import { ReportPageTemplate } from "@/components/templates/report-page";
import { ColumnDef } from "@tanstack/react-table";
import { UserRole } from "@/types/common";

interface SchoolReport {
  id: string;
  name: string;
  type: string;
  generatedBy: string;
  date: string;
  fileSize: string;
}

const reportCols: ColumnDef<SchoolReport>[] = [
  { accessorKey: "name", header: "Report Title" },
  { accessorKey: "type", header: "Domain Category" },
  { accessorKey: "generatedBy", header: "Generated By" },
  { accessorKey: "date", header: "Date Compiled" },
  { accessorKey: "fileSize", header: "File Size" },
];

const mockReports: SchoolReport[] = [
  { id: "rep-1", name: "Fee Collection Summary (May 2026)", type: "Finance / Fees", generatedBy: "Super Admin", date: "26 Jun 2026", fileSize: "1.4 MB" },
  { id: "rep-2", name: "Academic Final Results Grades Ledger", type: "Academic Exams", generatedBy: "Dean Office", date: "25 Jun 2026", fileSize: "2.8 MB" },
  { id: "rep-3", name: "Daily Attendance Compilation Report", type: "Attendance Logs", generatedBy: "System Scheduler", date: "26 Jun 2026", fileSize: "840 KB" },
  { id: "rep-4", name: "Vehicle Fuel & Payout Audit Report", type: "Fleet Transport", generatedBy: "Transport Manager", date: "24 Jun 2026", fileSize: "1.1 MB" },
  { id: "rep-5", name: "Hostel Occupancy Residents Log", type: "Hostel Warden", generatedBy: "Warden Account", date: "23 Jun 2026", fileSize: "670 KB" },
];

export default function SystemReportsPage({
  params,
}: {
  params: Promise<{ role: string }>;
}) {
  const resolvedParams = use(params);
  const role = resolvedParams.role as UserRole;

  if (role !== "super-admin" && role !== "branch-admin" && role !== "academic") {
    return (
      <div className="p-8 text-center text-xs text-muted-foreground">
        Access Denied.
      </div>
    );
  }

  const summaryKPIs = [
    { title: "Reports Compiled", value: "148 Reports", icon: FileText, color: "blue" as const },
    { title: "Automated Rules", value: "12 Cron Job", icon: Settings, color: "green" as const },
    { title: "Security Audits Logs", value: "240 Valid", icon: ShieldCheck, color: "purple" as const },
    { title: "Backup Cloud Storage", value: "2.4 GB Used", icon: Database, color: "orange" as const },
  ];

  const filters = (
    <>
      <div>
        <label className="text-[10px] font-bold text-muted-foreground block mb-1">Campus Branch</label>
        <select className="w-full h-8 border bg-card text-xs rounded-lg px-2">
          <option>All Branches Combined</option>
          <option>Delhi Main Branch</option>
          <option>Mumbai Campus</option>
        </select>
      </div>
      <div>
        <label className="text-[10px] font-bold text-muted-foreground block mb-1">Report Category Domain</label>
        <select className="w-full h-8 border bg-card text-xs rounded-lg px-2">
          <option>Fee Collection Ledger</option>
          <option>Student Academic Grades</option>
          <option>Employee Payroll Logs</option>
          <option>Library Catalog Issue Slip</option>
        </select>
      </div>
      <div>
        <label className="text-[10px] font-bold text-muted-foreground block mb-1">Academic Year</label>
        <select className="w-full h-8 border bg-card text-xs rounded-lg px-2">
          <option>2026 - 2027 (Current)</option>
          <option>2025 - 2026</option>
        </select>
      </div>
    </>
  );

  return (
    <ReportPageTemplate
      title="Analysis Dashboard & Report Builder"
      description="Compile, audit, and build customized reports across school financial and academic domains."
      data={mockReports}
      columns={reportCols}
      summaryKPIs={summaryKPIs}
      filterFields={filters}
      exportFileName="Greenwood_system_reports"
    />
  );
}
