import {
  LayoutDashboard,
  Building2,
  Users,
  GraduationCap,
  CalendarRange,
  ClipboardList,
  FileCheck,
  Briefcase,
  CreditCard,
  BookOpen,
  Package,
  Bus,
  Home,
  HeartPulse,
  History,
  Settings,
  FileText,
  MessageSquare,
  Calendar,
  UserCheck,
  BadgePercent,
  CheckSquare,
  Shield,
  HelpCircle,
} from "lucide-react";
import { SidebarConfig } from "@/types/sidebar";

export const sidebarConfigs: Record<string, SidebarConfig> = {
  "super-admin": {
    role: "super-admin",
    roleLabel: "Super Admin",
    items: [
      { label: "Dashboard Overview", icon: LayoutDashboard, href: "/super-admin/dashboard" },
      {
        label: "Branch Management",
        icon: Building2,
        children: [
          { label: "Branches List", href: "/super-admin/branch-management" },
          { label: "Add Branch", href: "/super-admin/branch-management/create" },
          { label: "Branch Admins", href: "/super-admin/branch-management/admins" },
          { label: "Performance Metrics", href: "/super-admin/branch-management/performance" },
        ],
      },
      {
        label: "Admission CRM",
        icon: Users,
        children: [
          { label: "CRM Dashboard", href: "/super-admin/admission-crm" },
          { label: "Leads Pipeline", href: "/super-admin/admission-crm/leads" },
          { label: "Inquiries List", href: "/super-admin/admission-crm/inquiries" },
          { label: "Counselor Allocation", href: "/super-admin/admission-crm/counselors" },
        ],
      },
      {
        label: "Student Directory",
        icon: GraduationCap,
        children: [
          { label: "All Students", href: "/super-admin/students" },
          { label: "Add Student", href: "/super-admin/students/create" },
          { label: "Student Passouts", href: "/super-admin/students/passouts" },
          { label: "Student Guard Details", href: "/super-admin/students/guardians" },
        ],
      },
      {
        label: "Academic Operations",
        icon: CalendarRange,
        children: [
          { label: "Class Management", href: "/super-admin/academic/classes" },
          { label: "Syllabus Manager", href: "/super-admin/academic/syllabus" },
          { label: "Timetable Master", href: "/super-admin/academic/timetable" },
        ],
      },
      {
        label: "Attendance Manager",
        icon: UserCheck,
        children: [
          { label: "Daily Attendance", href: "/super-admin/attendance" },
          { label: "Leave Requests", href: "/super-admin/attendance/leaves" },
        ],
      },
      {
        label: "Examinations & Grading",
        icon: FileCheck,
        children: [
          { label: "Exams Setup", href: "/super-admin/examinations" },
          { label: "Grade Cards", href: "/super-admin/examinations/grades" },
        ],
      },
      {
        label: "Staff & HR",
        icon: Briefcase,
        children: [
          { label: "Staff Directory", href: "/super-admin/staff-hr" },
          { label: "Recruitment Portal", href: "/super-admin/staff-hr/recruitment" },
        ],
      },
      {
        label: "Payroll Processing",
        icon: CheckSquare,
        children: [
          { label: "Salary Structure", href: "/super-admin/payroll/structure" },
          { label: "Process Payroll", href: "/super-admin/payroll/process" },
          { label: "Employee Payslips", href: "/super-admin/payroll/payslips" },
          { label: "Bonuses & Deductions", href: "/super-admin/payroll/bonuses" },
        ],
      },
      {
        label: "Fees & Accounts",
        icon: CreditCard,
        children: [
          { label: "Fee Structure", href: "/super-admin/fees-accounts/structure" },
          { label: "Fee Categories", href: "/super-admin/fees-accounts/categories" },
          { label: "Fee Collection", href: "/super-admin/fees-accounts/collection" },
          { label: "Pending Fees", href: "/super-admin/fees-accounts/pending" },
          { label: "Transactions Ledger", href: "/super-admin/fees-accounts/transactions" },
        ],
      },
      {
        label: "Library Operations",
        icon: BookOpen,
        children: [
          { label: "Books Catalog", href: "/super-admin/library/books" },
          { label: "Book Categories", href: "/super-admin/library/categories" },
          { label: "Issue & Return", href: "/super-admin/library/issue-return" },
          { label: "Fine Tracker", href: "/super-admin/library/fines" },
        ],
      },
      {
        label: "Inventory & Assets",
        icon: Package,
        children: [
          { label: "Products & Assets", href: "/super-admin/inventory/assets" },
          { label: "Product Categories", href: "/super-admin/inventory/categories" },
          { label: "Stock Levels", href: "/super-admin/inventory/stock" },
          { label: "Purchase Orders", href: "/super-admin/inventory/purchase-orders" },
        ],
      },
      {
        label: "Transport Management",
        icon: Bus,
        children: [
          { label: "Vehicles Fleet", href: "/super-admin/transport/vehicles" },
          { label: "Drivers Directory", href: "/super-admin/transport/drivers" },
          { label: "Routes & Stops", href: "/super-admin/transport/routes" },
          { label: "Fuel Logbook", href: "/super-admin/transport/fuel" },
        ],
      },
      {
        label: "Hostel Management",
        icon: Home,
        children: [
          { label: "Hostel Blocks", href: "/super-admin/hostel/blocks" },
          { label: "Rooms & Beds", href: "/super-admin/hostel/rooms-beds" },
          { label: "Bed Allocation", href: "/super-admin/hostel/allocation" },
        ],
      },
      {
        label: "Health Center",
        icon: HeartPulse,
        children: [
          { label: "Medical Records", href: "/super-admin/health-center/records" },
          { label: "Medical Visits", href: "/super-admin/health-center/visits" },
          { label: "Vaccinations", href: "/super-admin/health-center/vaccinations" },
          { label: "Medicine Inventory", href: "/super-admin/health-center/medicine" },
        ],
      },
      {
        label: "Visitor Management",
        icon: Users,
        children: [
          { label: "Visitor Log", href: "/super-admin/visitor-management/visitors" },
          { label: "Complaints Box", href: "/super-admin/visitor-management/complaints" },
        ],
      },
      {
        label: "Reports & Analytics",
        icon: FileText,
        children: [
          { label: "Main Dashboard", href: "/super-admin/reports" },
          { label: "Custom Export", href: "/super-admin/reports/export" },
        ],
      },
      {
        label: "System Logs",
        icon: History,
        children: [
          { label: "Audit Ledger", href: "/super-admin/audit-logs" },
          { label: "Session Activity", href: "/super-admin/audit-logs/activity" },
        ],
      },
      {
        label: "General Settings",
        icon: Settings,
        children: [
          { label: "School Settings", href: "/super-admin/settings" },
          { label: "User Roles & Access", href: "/super-admin/settings/roles" },
        ],
      },
    ],
  },
  "branch-admin": {
    role: "branch-admin",
    roleLabel: "Branch Admin",
    items: [
      {
        label: "Dashboard",
        icon: LayoutDashboard,
        children: [
          { label: "Overview", href: "/branch-admin/dashboard" },
          { label: "Today's Summary", href: "/branch-admin/dashboard/summary" },
          { label: "Notifications", href: "/branch-admin/dashboard/notifications" },
          { label: "Pending Approvals", href: "/branch-admin/dashboard/pending-approvals" },
          { label: "Branch Analytics", href: "/branch-admin/dashboard/analytics" },
        ],
      },
      {
        label: "Students",
        icon: GraduationCap,
        children: [
          { label: "Student List", href: "/branch-admin/students" },
          { label: "Add Student", href: "/branch-admin/students/create" },
          { label: "Student Profiles", href: "/branch-admin/students/profiles" },
          { label: "Student Documents", href: "/branch-admin/students/documents" },
          { label: "Student Categories", href: "/branch-admin/students/categories" },
          { label: "Parent Details", href: "/branch-admin/students/guardians" },
          { label: "Student Transfer", href: "/branch-admin/students/transfers" },
          { label: "Student Promotion", href: "/branch-admin/students/promotions" },
          { label: "ID Cards", href: "/branch-admin/students/id-cards" },
          { label: "Certificates", href: "/branch-admin/students/certificates" },
          { label: "Medical Records", href: "/branch-admin/students/medical" },
          { label: "Discipline Records", href: "/branch-admin/students/discipline" },
          { label: "Achievements", href: "/branch-admin/students/achievements" },
          { label: "Bulk Import", href: "/branch-admin/students/bulk-import" },
          { label: "Student Reports", href: "/branch-admin/students/reports" },
        ],
      },
      {
        label: "Admission CRM",
        icon: Briefcase,
        children: [
          { label: "CRM Dashboard", href: "/branch-admin/admission-crm" },
          { label: "CRM Inquiries", href: "/branch-admin/admission-crm/inquiries" },
          { label: "CRM Leads", href: "/branch-admin/admission-crm/leads" },
          { label: "Follow-Ups", href: "/branch-admin/admission-crm/follow-ups" },
          { label: "Admission Forms", href: "/branch-admin/admission-crm/forms" },
          { label: "Lead Sources", href: "/branch-admin/admission-crm/sources" },
          { label: "Counselors", href: "/branch-admin/admission-crm/counselors" },
          { label: "Admission Pipeline", href: "/branch-admin/admission-crm/pipeline" },
          { label: "Document Verification", href: "/branch-admin/admission-crm/verification" },
          { label: "Admission Approval", href: "/branch-admin/admission-crm/approval" },
          { label: "Conversion Reports", href: "/branch-admin/admission-crm/reports" },
          { label: "CRM Settings", href: "/branch-admin/admission-crm/settings" },
        ],
      },
      {
        label: "Academic",
        icon: BookOpen,
        children: [
          { label: "Classes", href: "/branch-admin/classes-sections" },
          { label: "Sections", href: "/branch-admin/classes-sections" },
          { label: "Subjects", href: "/branch-admin/subjects" },
          { label: "Timetable", href: "/branch-admin/timetable" },
          { label: "Academic Calendar", href: "/branch-admin/academic-calendar" },
          { label: "Syllabus Monitor", href: "/branch-admin/syllabus" },
        ],
      },
      {
        label: "Attendance",
        icon: UserCheck,
        children: [
          { label: "Student Attendance", href: "/branch-admin/attendance" },
          { label: "Teacher Attendance", href: "/branch-admin/attendance/teacher" },
          { label: "Staff Attendance", href: "/branch-admin/attendance/staff" },
          { label: "Attendance Reports", href: "/branch-admin/attendance/reports" },
          { label: "Leave Requests", href: "/branch-admin/attendance/leaves" },
          { label: "Leave Reports", href: "/branch-admin/attendance/leave-reports" },
          { label: "Monthly Reports", href: "/branch-admin/attendance/monthly" },
          { label: "Holiday Calendar", href: "/branch-admin/attendance/holiday-calendar" },
          { label: "Attendance Settings", href: "/branch-admin/attendance/settings" },
        ],
      },
      {
        label: "Examination",
        icon: FileCheck,
        children: [
          { label: "Exam Setup", href: "/branch-admin/examinations" },
          { label: "Marks Entry", href: "/branch-admin/examinations" },
          { label: "Result Processing", href: "/branch-admin/examinations" },
          { label: "Report Cards", href: "/branch-admin/examinations" },
          { label: "Grades & GPA", href: "/branch-admin/examinations/grades" },
        ],
      },
      {
        label: "Staff Management",
        icon: Users,
        children: [
          { label: "Staff List", href: "/branch-admin/employees" },
          { label: "Departments", href: "/branch-admin/employees" },
          { label: "Leave Management", href: "/branch-admin/attendance/leaves" },
          { label: "Staff Documents", href: "/branch-admin/employees" },
          { label: "All Users", href: "/branch-admin/user-management" },
          { label: "Create User", href: "/branch-admin/user-management/create" },
          { label: "Role Management", href: "/branch-admin/user-management/roles" },
          { label: "Permissions", href: "/branch-admin/user-management/permissions" },
          { label: "Academic Users", href: "/branch-admin/user-management/academic" },
          { label: "Finance Users", href: "/branch-admin/user-management/finance" },
          { label: "HR Users", href: "/branch-admin/user-management/hr" },
          { label: "Library Users", href: "/branch-admin/user-management/library" },
          { label: "Transport Users", href: "/branch-admin/user-management/transport" },
          { label: "Hostel Users", href: "/branch-admin/user-management/hostel" },
          { label: "Teacher Users", href: "/branch-admin/user-management/teachers" },
          { label: "Login Activity Logs", href: "/branch-admin/user-management/logs" },
        ],
      },
      {
        label: "Fees",
        icon: CreditCard,
        children: [
          { label: "Fee Collection", href: "/branch-admin/fee-collection" },
          { label: "Fee Structure", href: "/branch-admin/fee-management" },
          { label: "Discounts & Approvals", href: "/branch-admin/approvals/discounts" },
          { label: "Due Management", href: "/branch-admin/due-management" },
          { label: "Scholarships", href: "/branch-admin/approvals/scholarships" },
          { label: "Admissions Approvals", href: "/branch-admin/approvals/admissions" },
          { label: "Transfers Approvals", href: "/branch-admin/approvals/transfers" },
          { label: "Expense Approvals", href: "/branch-admin/approvals/expenses" },
          { label: "Purchase Requests", href: "/branch-admin/approvals/purchase" },
          { label: "Staff Requests", href: "/branch-admin/approvals/staff" },
          { label: "Pending Summary", href: "/branch-admin/approvals/pending" },
        ],
      },
      {
        label: "Payroll",
        icon: ClipboardList,
        children: [
          { label: "Payroll Processing", href: "/branch-admin/payroll" },
          { label: "Payslips", href: "/branch-admin/payroll" },
          { label: "Salary Structure", href: "/branch-admin/payroll" },
          { label: "Payroll Reports", href: "/branch-admin/payroll" },
        ],
      },
      {
        label: "Library",
        icon: BookOpen,
        children: [
          { label: "Books Catalog", href: "/branch-admin/books" },
          { label: "Issue / Return", href: "/branch-admin/issue-return" },
          { label: "Fine Management", href: "/branch-admin/fines" },
          { label: "Library Reports", href: "/branch-admin/reports/library" },
        ],
      },
      {
        label: "Inventory",
        icon: Package,
        children: [
          { label: "Products & Assets", href: "/branch-admin/inventory/assets" },
          { label: "Product Categories", href: "/branch-admin/inventory/categories" },
          { label: "Stock Levels", href: "/branch-admin/inventory/stock" },
          { label: "Purchase Orders", href: "/branch-admin/inventory/purchase-orders" },
        ],
      },
      {
        label: "Transport",
        icon: Bus,
        children: [
          { label: "Vehicles Fleet", href: "/branch-admin/transport/vehicles" },
          { label: "Drivers Directory", href: "/branch-admin/transport/drivers" },
          { label: "Routes & Stops", href: "/branch-admin/transport/routes" },
          { label: "Fuel Logbook", href: "/branch-admin/transport/fuel" },
        ],
      },
      {
        label: "Hostel",
        icon: Home,
        children: [
          { label: "Hostel Blocks", href: "/branch-admin/hostel/blocks" },
          { label: "Rooms & Beds", href: "/branch-admin/hostel/rooms-beds" },
          { label: "Bed Allocation", href: "/branch-admin/hostel/allocation" },
        ],
      },
      {
        label: "Reports",
        icon: FileText,
        children: [
          { label: "Report Builder", href: "/branch-admin/reports" },
          { label: "Student Reports", href: "/branch-admin/reports/students" },
          { label: "Admission Reports", href: "/branch-admin/reports/admission" },
          { label: "Attendance Reports", href: "/branch-admin/reports/attendance" },
          { label: "Academic Reports", href: "/branch-admin/reports/academic" },
          { label: "Finance Reports", href: "/branch-admin/reports/finance" },
          { label: "Payroll Reports", href: "/branch-admin/reports/payroll" },
          { label: "Library Reports", href: "/branch-admin/reports/library" },
          { label: "Transport Reports", href: "/branch-admin/reports/transport" },
          { label: "Hostel Reports", href: "/branch-admin/reports/hostel" },
          { label: "HR Reports", href: "/branch-admin/reports/hr" },
          { label: "Custom Reports", href: "/branch-admin/reports/custom" },
          { label: "Analytics Dashboard", href: "/branch-admin/reports/analytics" },
          { label: "Daily Reports", href: "/branch-admin/reports/daily" },
          { label: "Monthly Reports", href: "/branch-admin/reports/monthly" },
          { label: "Yearly Reports", href: "/branch-admin/reports/yearly" },
          { label: "PDF Export Utility", href: "/branch-admin/reports/pdf" },
          { label: "Excel Export Utility", href: "/branch-admin/reports/excel" },
          { label: "Scheduled Reports", href: "/branch-admin/reports/scheduled" },
          { label: "Audit Reports", href: "/branch-admin/reports/audit" },
          { label: "Performance Reports", href: "/branch-admin/reports/performance" },
        ],
      },
      {
        label: "Communications",
        icon: MessageSquare,
        children: [
          { label: "Notice Board", href: "/branch-admin/communications" },
          { label: "SMS Broadcast", href: "/branch-admin/communications/sms" },
          { label: "Email Broadcast", href: "/branch-admin/communications/email" },
          { label: "WhatsApp Broadcast", href: "/branch-admin/communications/whatsapp" },
          { label: "Message Templates", href: "/branch-admin/communications/templates" },
          { label: "Push Notifications", href: "/branch-admin/communications/push" },
          { label: "Parent Messages", href: "/branch-admin/communications/parent" },
          { label: "Teacher Messages", href: "/branch-admin/communications/teacher" },
          { label: "Communication Logs", href: "/branch-admin/communications/logs" },
        ],
      },
      {
        label: "Settings",
        icon: Settings,
        children: [
          { label: "Profile Settings", href: "/branch-admin/settings" },
          { label: "Academic Settings", href: "/branch-admin/settings/academic" },
          { label: "Admission Settings", href: "/branch-admin/settings/admission" },
          { label: "Fee Settings", href: "/branch-admin/settings/fee" },
          { label: "Attendance Settings", href: "/branch-admin/settings/attendance" },
          { label: "Communication Settings", href: "/branch-admin/settings/communication" },
          { label: "Logo Configuration", href: "/branch-admin/settings/logo" },
          { label: "Theme Configuration", href: "/branch-admin/settings/theme" },
          { label: "Session Management", href: "/branch-admin/settings/sessions" },
          { label: "Password Policy", href: "/branch-admin/settings/password-policy" },
          { label: "Backup Configurations", href: "/branch-admin/settings/backup" },
          { label: "Restore Configurations", href: "/branch-admin/settings/restore" },
          { label: "Security Configurations", href: "/branch-admin/settings/security" },
          { label: "Third-party Integrations", href: "/branch-admin/settings/integrations" },
          { label: "General Settings", href: "/branch-admin/settings/general" },
        ],
      },
    ],
  },
  academic: {
    role: "academic",
    roleLabel: "Academic Head",
    items: [
      {
        label: "Dashboard",
        icon: LayoutDashboard,
        children: [
          { label: "Overview", href: "/academic/dashboard" },
          { label: "Academic Analytics", href: "/academic/dashboard/analytics" },
          { label: "Attendance Analytics", href: "/academic/dashboard/attendance-analytics" },
          { label: "Exam Analytics", href: "/academic/dashboard/exam-analytics" },
          { label: "Notifications", href: "/academic/dashboard/notifications" },
        ],
      },
      {
        label: "Classes & Sections",
        icon: Building2,
        children: [
          { label: "All Classes", href: "/academic/classes-sections" },
          { label: "Create Class", href: "/academic/classes-sections/create" },
          { label: "Sections List", href: "/academic/classes-sections/sections" },
          { label: "Assign Class Teacher", href: "/academic/classes-sections/assign-teacher" },
          { label: "Class Capacity", href: "/academic/classes-sections/capacity" },
          { label: "Class Overview", href: "/academic/classes-sections/overview" },
          { label: "Class Reports", href: "/academic/classes-sections/reports" },
        ],
      },
      {
        label: "Subjects",
        icon: BookOpen,
        children: [
          { label: "All Subjects", href: "/academic/subjects" },
          { label: "Create Subject", href: "/academic/subjects/create" },
          { label: "Subject Allocation", href: "/academic/subjects/allocations" },
          { label: "Subject Mapping", href: "/academic/subjects/mapping" },
          { label: "Subject Teachers", href: "/academic/subjects/teachers" },
          { label: "Subject Credits", href: "/academic/subjects/credits" },
          { label: "Subject Reports", href: "/academic/subjects/reports" },
          { label: "Subject Settings", href: "/academic/subjects/settings" },
        ],
      },
      {
        label: "Timetable",
        icon: CalendarRange,
        children: [
          { label: "Master Timetable", href: "/academic/timetable" },
          { label: "Class Timetable", href: "/academic/timetable/class" },
          { label: "Teacher Timetable", href: "/academic/timetable/teacher" },
          { label: "Room Allocation", href: "/academic/timetable/rooms" },
          { label: "Period Management", href: "/academic/timetable/periods" },
          { label: "Substitute Teacher", href: "/academic/timetable/substitutes" },
          { label: "Exam Timetable", href: "/academic/timetable/exams" },
          { label: "Timetable Generator", href: "/academic/timetable/generator" },
          { label: "Timetable Reports", href: "/academic/timetable/reports" },
        ],
      },
      {
        label: "Academic Calendar",
        icon: Calendar,
        children: [
          { label: "Academic Session", href: "/academic/academic-calendar" },
          { label: "School Events", href: "/academic/academic-calendar/events" },
          { label: "Holidays", href: "/academic/academic-calendar/holidays" },
          { label: "Exam Calendar", href: "/academic/academic-calendar/exams" },
          { label: "PTM Schedule", href: "/academic/academic-calendar/ptm" },
          { label: "Special Events", href: "/academic/academic-calendar/special" },
          { label: "Calendar Reports", href: "/academic/academic-calendar/reports" },
        ],
      },
      {
        label: "Syllabus Management",
        icon: ClipboardList,
        children: [
          { label: "Upload Syllabus", href: "/academic/syllabus" },
          { label: "Subject Syllabus", href: "/academic/syllabus/subject" },
          { label: "Chapter Management", href: "/academic/syllabus/chapters" },
          { label: "Lesson Planning", href: "/academic/syllabus/lessons" },
          { label: "Completion Tracking", href: "/academic/syllabus/tracking" },
          { label: "Teacher Progress", href: "/academic/syllabus/teachers" },
          { label: "Class Progress", href: "/academic/syllabus/classes" },
          { label: "Subject Progress", href: "/academic/syllabus/subjects" },
          { label: "Syllabus Reports", href: "/academic/syllabus/reports" },
        ],
      },
      {
        label: "Attendance Monitoring",
        icon: UserCheck,
        children: [
          { label: "Student Attendance", href: "/academic/attendance" },
          { label: "Class Attendance", href: "/academic/attendance/class" },
          { label: "Subject Attendance", href: "/academic/attendance/subject" },
          { label: "Teacher Attendance", href: "/academic/attendance/teacher" },
          { label: "Attendance Analytics", href: "/academic/attendance/analytics" },
          { label: "Attendance Reports", href: "/academic/attendance/reports" },
          { label: "Defaulters List", href: "/academic/attendance/defaulters" },
          { label: "Attendance Trends", href: "/academic/attendance/trends" },
          { label: "Monthly Reports", href: "/academic/attendance/monthly" },
        ],
      },
      {
        label: "Examinations",
        icon: FileCheck,
        children: [
          { label: "Exam Setup", href: "/academic/examinations" },
          { label: "Exam Types", href: "/academic/examinations/types" },
          { label: "Exam Schedule", href: "/academic/examinations/schedule" },
          { label: "Exam Centers", href: "/academic/examinations/centers" },
          { label: "Hall Allocation", href: "/academic/examinations/halls" },
          { label: "Invigilator Assignment", href: "/academic/examinations/invigilators" },
          { label: "Question Bank", href: "/academic/examinations/questions" },
          { label: "Exam Instructions", href: "/academic/examinations/instructions" },
          { label: "Marks Entry", href: "/academic/examinations/marks" },
          { label: "Practical Exams", href: "/academic/examinations/practical" },
          { label: "Exam Analytics", href: "/academic/examinations/analytics" },
          { label: "Grade System", href: "/academic/examinations/grades" },
          { label: "Exam Reports", href: "/academic/examinations/reports" },
          { label: "Result Processing", href: "/academic/examinations/results" },
        ],
      },
      {
        label: "Result Monitoring",
        icon: CheckSquare,
        children: [
          { label: "Result Verification", href: "/academic/results" },
          { label: "Publish Results", href: "/academic/results/publish" },
          { label: "Class Results", href: "/academic/results/classes" },
          { label: "Student Results", href: "/academic/results/students" },
          { label: "Subject Results", href: "/academic/results/subjects" },
          { label: "Rank Lists", href: "/academic/results/ranks" },
          { label: "Top Performers", href: "/academic/results/top" },
          { label: "Fail Analysis", href: "/academic/results/failures" },
          { label: "Grade Analysis", href: "/academic/results/grades" },
          { label: "Result Analytics", href: "/academic/results/analytics" },
          { label: "Report Cards", href: "/academic/results/report-cards" },
        ],
      },
      {
        label: "Teachers",
        icon: Users,
        children: [
          { label: "Teacher Directory", href: "/academic/teachers" },
          { label: "Teacher Allocation", href: "/academic/teachers/allocations" },
          { label: "Teacher Workload", href: "/academic/teachers/workloads" },
          { label: "Teacher Timetable", href: "/academic/teachers/timetable" },
          { label: "Teacher Attendance", href: "/academic/teachers/attendance" },
          { label: "Teacher Performance", href: "/academic/teachers/performance" },
          { label: "Observations Logs", href: "/academic/teachers/observations" },
          { label: "Training Programs", href: "/academic/teachers/training" },
          { label: "Appraisals Panel", href: "/academic/teachers/appraisals" },
          { label: "Teacher Reports", href: "/academic/teachers/reports" },
          { label: "Teacher Documents", href: "/academic/teachers/documents" },
        ],
      },
      {
        label: "Students Performance",
        icon: GraduationCap,
        children: [
          { label: "Student Performance", href: "/academic/students-performance" },
          { label: "Class Performance", href: "/academic/students-performance/classes" },
          { label: "Subject Performance", href: "/academic/students-performance/subjects" },
          { label: "Student Ranking", href: "/academic/students-performance/ranks" },
          { label: "Progress Tracking", href: "/academic/students-performance/progress" },
          { label: "Weak Students", href: "/academic/students-performance/weak" },
          { label: "Top Performers", href: "/academic/students-performance/top" },
          { label: "Performance Analytics", href: "/academic/students-performance/analytics" },
          { label: "Report Cards Print", href: "/academic/students-performance/report-cards" },
          { label: "Student Comparisons", href: "/academic/students-performance/comparisons" },
          { label: "Improvement Plans", href: "/academic/students-performance/improvements" },
        ],
      },
      {
        label: "Reports",
        icon: FileText,
        children: [
          { label: "Academic Reports", href: "/academic/reports" },
          { label: "Attendance Reports", href: "/academic/reports/attendance" },
          { label: "Exam Reports", href: "/academic/reports/exams" },
          { label: "Result Reports", href: "/academic/reports/results" },
          { label: "Teacher Reports", href: "/academic/reports/teachers" },
          { label: "Class Reports", href: "/academic/reports/classes" },
          { label: "Subject Reports", href: "/academic/reports/subjects" },
          { label: "Performance Reports", href: "/academic/reports/performance" },
          { label: "Defaulter Reports", href: "/academic/reports/defaulters" },
          { label: "Promotion Reports", href: "/academic/reports/promotions" },
          { label: "PDF Export Utility", href: "/academic/reports/pdf" },
          { label: "Excel Export Utility", href: "/academic/reports/excel" },
          { label: "Custom Reports", href: "/academic/reports/custom" },
          { label: "Scheduled Reports", href: "/academic/reports/scheduled" },
          { label: "Analytics Reports", href: "/academic/reports/analytics" },
        ],
      },
      {
        label: "Communications",
        icon: MessageSquare,
        children: [
          { label: "Notice Board", href: "/academic/communications" },
          { label: "Teacher Messages", href: "/academic/communications/teacher" },
          { label: "Student Messages", href: "/academic/communications/student" },
          { label: "Parent Messages", href: "/academic/communications/parent" },
          { label: "SMS Broadcasts", href: "/academic/communications/sms" },
          { label: "Email Broadcasts", href: "/academic/communications/email" },
        ],
      },
      {
        label: "Settings",
        icon: Settings,
        children: [
          { label: "Academic Settings", href: "/academic/settings" },
          { label: "Exam Settings", href: "/academic/settings/exams" },
          { label: "Attendance Settings", href: "/academic/settings/attendance" },
          { label: "Result Settings", href: "/academic/settings/results" },
          { label: "Promotion Rules", href: "/academic/settings/promotion" },
          { label: "Grade Settings", href: "/academic/settings/grading" },
          { label: "Session Settings", href: "/academic/settings/sessions" },
          { label: "Subject Settings", href: "/academic/settings/subjects" },
          { label: "Calendar Settings", href: "/academic/settings/calendar" },
          { label: "General Settings", href: "/academic/settings/general" },
        ],
      },
    ],
  },
  finance: {
    role: "finance",
    roleLabel: "Finance Manager",
    items: [
      { label: "Financial Dashboard", icon: LayoutDashboard, href: "/finance/dashboard" },
      {
        label: "Fee Operations",
        icon: CreditCard,
        children: [
          { label: "Fees Overview", href: "/finance/fee-management" },
          { label: "Collect Fee", href: "/finance/fee-collection" },
          { label: "Due Reminders", href: "/finance/due-management" },
          { label: "Refund Requests", href: "/finance/refunds" },
        ],
      },
      { label: "Expense Register", icon: CheckSquare, href: "/finance/expenses" },
      { label: "Income Ledger", icon: BadgePercent, href: "/finance/income" },
      { label: "Salary Payroll", icon: Briefcase, href: "/finance/salary-payroll" },
      { label: "Scholarship Grants", icon: GraduationCap, href: "/finance/scholarships" },
      { label: "Bank Reconciliation", icon: Building2, href: "/finance/bank-accounts" },
      { label: "Financial Audits", icon: FileText, href: "/finance/reports" },
      { label: "Approvals Desk", icon: Shield, href: "/finance/approvals" },
      { label: "Finance Settings", icon: Settings, href: "/finance/settings" },
    ],
  },
  hr: {
    role: "hr",
    roleLabel: "HR Manager",
    items: [
      { label: "HR Dashboard", icon: LayoutDashboard, href: "/hr/dashboard" },
      {
        label: "Employees",
        icon: Users,
        children: [
          { label: "Employee List", href: "/hr/employees" },
          { label: "Add Employee", href: "/hr/employees/create" },
          { label: "Employee Directory", href: "/hr/directory" },
        ],
      },
      { label: "Attendance logs", icon: UserCheck, href: "/hr/attendance" },
      { label: "Leave Desk", icon: Calendar, href: "/hr/leave" },
      { label: "HR Payroll", icon: CreditCard, href: "/hr/payroll" },
      { label: "Recruiting Pipeline", icon: Briefcase, href: "/hr/recruitment" },
      { label: "Performance Appraisals", icon: CheckSquare, href: "/hr/performance" },
      { label: "Asset Allocation", icon: Package, href: "/hr/assets" },
      { label: "Company Documents", icon: FileText, href: "/hr/documents" },
      { label: "General Settings", icon: Settings, href: "/hr/settings" },
    ],
  },
  library: {
    role: "library",
    roleLabel: "Librarian",
    items: [
      { label: "Library Home", icon: LayoutDashboard, href: "/library/dashboard" },
      { label: "Catalog Books", icon: BookOpen, href: "/library/books" },
      { label: "Issue & Return", icon: ClipboardList, href: "/library/issue-return" },
      { label: "Library Members", icon: Users, href: "/library/members" },
      { label: "Fine Ledger", icon: CreditCard, href: "/library/fines" },
      { label: "Activity Logs", icon: History, href: "/library/transactions" },
      { label: "Reports Module", icon: FileText, href: "/library/reports" },
      { label: "Library Settings", icon: Settings, href: "/library/settings" },
    ],
  },
  transport: {
    role: "transport",
    roleLabel: "Transport Admin",
    items: [
      { label: "Fleet Dashboard", icon: LayoutDashboard, href: "/transport/dashboard" },
      { label: "Vehicle Register", icon: Bus, href: "/transport/vehicles" },
      { label: "Routes & Stoppages", icon: Building2, href: "/transport/routes" },
      { label: "Staff & Drivers", icon: Users, href: "/transport/drivers" },
      { label: "GPS Route Allocations", icon: UserCheck, href: "/transport/allocation" },
      { label: "Fuel Expenses", icon: CreditCard, href: "/transport/fuel" },
      { label: "Attendance Log", icon: ClipboardList, href: "/transport/attendance" },
      { label: "Trips History", icon: History, href: "/transport/trips" },
      { label: "General Settings", icon: Settings, href: "/transport/settings" },
    ],
  },
  hostel: {
    role: "hostel",
    roleLabel: "Hostel Warden",
    items: [
      { label: "Hostel Dashboard", icon: LayoutDashboard, href: "/hostel/dashboard" },
      { label: "Rooms & Beds Layout", icon: Home, href: "/hostel/rooms-beds" },
      { label: "Student Residents", icon: Users, href: "/hostel/students" },
      { label: "Allotment Desk", icon: ClipboardList, href: "/hostel/allocation" },
      { label: "Leave Log", icon: Calendar, href: "/hostel/leave" },
      { label: "Guest Logs", icon: UserCheck, href: "/hostel/visitors" },
      { label: "Complaints Register", icon: HelpCircle, href: "/hostel/complaints" },
      { label: "Billing & Fees", icon: CreditCard, href: "/hostel/finance" },
      { label: "Hostel Reports", icon: FileText, href: "/hostel/reports" },
      { label: "Warden Settings", icon: Settings, href: "/hostel/settings" },
    ],
  },
  teacher: {
    role: "teacher",
    roleLabel: "Educator",
    items: [
      { label: "My Dashboard", icon: LayoutDashboard, href: "/teacher/dashboard" },
      { label: "My Classes", icon: GraduationCap, href: "/teacher/my-classes" },
      { label: "Roll Call", icon: UserCheck, href: "/teacher/attendance" },
      { label: "Homework Desk", icon: ClipboardList, href: "/teacher/homework" },
      { label: "Exam Marks Entry", icon: FileCheck, href: "/teacher/examinations" },
      { label: "Class Timetable", icon: Calendar, href: "/teacher/timetable" },
      { label: "Notice Board", icon: FileText, href: "/teacher/notice-board" },
      { label: "Student Chats", icon: MessageSquare, href: "/teacher/messages" },
      { label: "Leave Requests", icon: CalendarRange, href: "/teacher/leave" },
      { label: "My Profile", icon: Users, href: "/teacher/profile" },
    ],
  },
  student: {
    role: "student",
    roleLabel: "Student",
    items: [
      { label: "My Portal", icon: LayoutDashboard, href: "/student/dashboard" },
      { label: "My Profile", icon: Users, href: "/student/profile" },
      { label: "Attendance Sheet", icon: UserCheck, href: "/student/attendance" },
      { label: "Timetable Schedule", icon: Calendar, href: "/student/timetable" },
      { label: "Assignments & Homework", icon: ClipboardList, href: "/student/homework" },
      { label: "My Exams", icon: FileCheck, href: "/student/examinations" },
      { label: "Results / Report Card", icon: FileText, href: "/student/results" },
      { label: "Fee Ledger", icon: CreditCard, href: "/student/fees" },
      { label: "Library Catalog", icon: BookOpen, href: "/student/library" },
      { label: "Bus Route Status", icon: Bus, href: "/student/transport" },
      { label: "Leave Application", icon: CalendarRange, href: "/student/leave" },
      { label: "Inbox Messages", icon: MessageSquare, href: "/student/messages" },
    ],
  },
  parent: {
    role: "parent",
    roleLabel: "Parent",
    items: [
      { label: "Dashboard", icon: LayoutDashboard, href: "/parent/dashboard" },
      { label: "My Children Profiles", icon: Users, href: "/parent/my-children" },
      { label: "Kids Attendance", icon: UserCheck, href: "/parent/attendance" },
      { label: "Fee Invoices", icon: CreditCard, href: "/parent/fees" },
      { label: "Class Timetables", icon: Calendar, href: "/parent/timetable" },
      { label: "Homework Status", icon: ClipboardList, href: "/parent/homework" },
      { label: "Grade Sheets", icon: FileText, href: "/parent/results" },
      { label: "School Notices", icon: FileText, href: "/parent/notices" },
      { label: "School Calendar", icon: CalendarRange, href: "/parent/calendar" },
      { label: "Teacher Messages", icon: MessageSquare, href: "/parent/messages" },
      { label: "Apply Leave", icon: Calendar, href: "/parent/leave" },
      { label: "Transport Info", icon: Bus, href: "/parent/transport" },
      { label: "Library Accounts", icon: BookOpen, href: "/parent/library" },
    ],
  },
};
