import {
  LayoutDashboard,
  Building2,
  Users,
  GraduationCap,
  CalendarRange,
  ClipboardList,
  FileCheck,
  Briefcase,
  CreditCard,
  BookOpen,
  Package,
  Bus,
  Home,
  HeartPulse,
  History,
  Settings,
  FileText,
  MessageSquare,
  Calendar,
  UserCheck,
  BadgePercent,
  CheckSquare,
  Shield,
  HelpCircle,
} from "lucide-react";
import { SidebarConfig } from "@/types/sidebar";

export const sidebarConfigs: Record<string, SidebarConfig> = {
  "super-admin": {
    role: "super-admin",
    roleLabel: "Super Admin",
    items: [
      { label: "Dashboard Overview", icon: LayoutDashboard, href: "/super-admin/dashboard" },
      {
        label: "Branch Management",
        icon: Building2,
        children: [
          { label: "Branches List", href: "/super-admin/branch-management" },
          { label: "Add Branch", href: "/super-admin/branch-management/create" },
          { label: "Branch Admins", href: "/super-admin/branch-management/admins" },
          { label: "Performance Metrics", href: "/super-admin/branch-management/performance" },
        ],
      },
      {
        label: "Admission CRM",
        icon: Users,
        children: [
          { label: "CRM Dashboard", href: "/super-admin/admission-crm" },
          { label: "Leads Pipeline", href: "/super-admin/admission-crm/leads" },
          { label: "Inquiries List", href: "/super-admin/admission-crm/inquiries" },
          { label: "Counselor Allocation", href: "/super-admin/admission-crm/counselors" },
        ],
      },
      {
        label: "Student Directory",
        icon: GraduationCap,
        children: [
          { label: "All Students", href: "/super-admin/students" },
          { label: "Add Student", href: "/super-admin/students/create" },
          { label: "Student Passouts", href: "/super-admin/students/passouts" },
          { label: "Student Guard Details", href: "/super-admin/students/guardians" },
        ],
      },
      {
        label: "Academic Operations",
        icon: CalendarRange,
        children: [
          { label: "Class Management", href: "/super-admin/academic/classes" },
          { label: "Syllabus Manager", href: "/super-admin/academic/syllabus" },
          { label: "Timetable Master", href: "/super-admin/academic/timetable" },
        ],
      },
      {
        label: "Attendance Manager",
        icon: UserCheck,
        children: [
          { label: "Daily Attendance", href: "/super-admin/attendance" },
          { label: "Leave Requests", href: "/super-admin/attendance/leaves" },
        ],
      },
      {
        label: "Examinations & Grading",
        icon: FileCheck,
        children: [
          { label: "Exams Setup", href: "/super-admin/examinations" },
          { label: "Grade Cards", href: "/super-admin/examinations/grades" },
        ],
      },
      {
        label: "Staff & HR",
        icon: Briefcase,
        children: [
          { label: "Staff Directory", href: "/super-admin/staff-hr" },
          { label: "Recruitment Portal", href: "/super-admin/staff-hr/recruitment" },
        ],
      },
      { label: "Payroll Processing", icon: CheckSquare, href: "/super-admin/payroll" },
      { label: "Fees & Accounts", icon: CreditCard, href: "/super-admin/fees-accounts" },
      { label: "Library Operations", icon: BookOpen, href: "/super-admin/library" },
      { label: "Inventory & Assets", icon: Package, href: "/super-admin/inventory" },
      { label: "Transport Management", icon: Bus, href: "/super-admin/transport" },
      { label: "Hostel Management", icon: Home, href: "/super-admin/hostel" },
      { label: "Visitor Management", icon: Users, href: "/super-admin/visitor-management" },
      { label: "Reports & Analytics", icon: FileText, href: "/super-admin/reports" },
      { label: "System Logs", icon: History, href: "/super-admin/audit-logs" },
      { label: "General Settings", icon: Settings, href: "/super-admin/settings" },
    ],
  },
  "branch-admin": {
    role: "branch-admin",
    roleLabel: "Branch Admin",
    items: [
      { label: "Dashboard", icon: LayoutDashboard, href: "/branch-admin/dashboard" },
      {
        label: "User Management",
        icon: Users,
        children: [
          { label: "All Users", href: "/branch-admin/user-management" },
          { label: "Roles & Permissions", href: "/branch-admin/user-management/permissions" },
        ],
      },
      { label: "Student Directory", icon: GraduationCap, href: "/branch-admin/students" },
      { label: "Admission CRM", icon: Briefcase, href: "/branch-admin/admission-crm" },
      { label: "Attendance Portal", icon: UserCheck, href: "/branch-admin/attendance" },
      { label: "Administrative Reports", icon: FileText, href: "/branch-admin/reports" },
      { label: "Approvals Feed", icon: CheckSquare, href: "/branch-admin/approvals" },
      { label: "Branch Settings", icon: Settings, href: "/branch-admin/settings" },
    ],
  },
  academic: {
    role: "academic",
    roleLabel: "Academic Head",
    items: [
      { label: "Academic Dashboard", icon: LayoutDashboard, href: "/academic/dashboard" },
      {
        label: "Classes & Sections",
        icon: Building2,
        children: [
          { label: "Class List", href: "/academic/classes-sections" },
          { label: "Subject Allocation", href: "/academic/classes-sections/allocations" },
        ],
      },
      { label: "Subjects Catalog", icon: BookOpen, href: "/academic/subjects" },
      { label: "Timetable Manager", icon: CalendarRange, href: "/academic/timetable" },
      { label: "Academic Calendar", icon: Calendar, href: "/academic/academic-calendar" },
      { label: "Syllabus Monitor", icon: FileText, href: "/academic/syllabus" },
      { label: "Attendance Tracking", icon: UserCheck, href: "/academic/attendance" },
      { label: "Exam Configurations", icon: FileCheck, href: "/academic/examinations" },
      { label: "Results Ledger", icon: CheckSquare, href: "/academic/results" },
      { label: "Teacher Directory", icon: Users, href: "/academic/teachers" },
      { label: "Academic Reports", icon: FileText, href: "/academic/reports" },
      { label: "Portal Settings", icon: Settings, href: "/academic/settings" },
    ],
  },
  finance: {
    role: "finance",
    roleLabel: "Finance Manager",
    items: [
      { label: "Financial Dashboard", icon: LayoutDashboard, href: "/finance/dashboard" },
      {
        label: "Fee Operations",
        icon: CreditCard,
        children: [
          { label: "Fees Overview", href: "/finance/fee-management" },
          { label: "Collect Fee", href: "/finance/fee-collection" },
          { label: "Due Reminders", href: "/finance/due-management" },
          { label: "Refund Requests", href: "/finance/refunds" },
        ],
      },
      { label: "Expense Register", icon: CheckSquare, href: "/finance/expenses" },
      { label: "Income Ledger", icon: BadgePercent, href: "/finance/income" },
      { label: "Salary Payroll", icon: Briefcase, href: "/finance/salary-payroll" },
      { label: "Scholarship Grants", icon: GraduationCap, href: "/finance/scholarships" },
      { label: "Bank Reconciliation", icon: Building2, href: "/finance/bank-accounts" },
      { label: "Financial Audits", icon: FileText, href: "/finance/reports" },
      { label: "Approvals Desk", icon: Shield, href: "/finance/approvals" },
      { label: "Finance Settings", icon: Settings, href: "/finance/settings" },
    ],
  },
  hr: {
    role: "hr",
    roleLabel: "HR Manager",
    items: [
      { label: "HR Dashboard", icon: LayoutDashboard, href: "/hr/dashboard" },
      {
        label: "Employees",
        icon: Users,
        children: [
          { label: "Employee List", href: "/hr/employees" },
          { label: "Add Employee", href: "/hr/employees/create" },
          { label: "Employee Directory", href: "/hr/directory" },
        ],
      },
      { label: "Attendance logs", icon: UserCheck, href: "/hr/attendance" },
      { label: "Leave Desk", icon: Calendar, href: "/hr/leave" },
      { label: "HR Payroll", icon: CreditCard, href: "/hr/payroll" },
      { label: "Recruiting Pipeline", icon: Briefcase, href: "/hr/recruitment" },
      { label: "Performance Appraisals", icon: CheckSquare, href: "/hr/performance" },
      { label: "Asset Allocation", icon: Package, href: "/hr/assets" },
      { label: "Company Documents", icon: FileText, href: "/hr/documents" },
      { label: "General Settings", icon: Settings, href: "/hr/settings" },
    ],
  },
  library: {
    role: "library",
    roleLabel: "Librarian",
    items: [
      { label: "Library Home", icon: LayoutDashboard, href: "/library/dashboard" },
      { label: "Catalog Books", icon: BookOpen, href: "/library/books" },
      { label: "Issue & Return", icon: ClipboardList, href: "/library/issue-return" },
      { label: "Library Members", icon: Users, href: "/library/members" },
      { label: "Fine Ledger", icon: CreditCard, href: "/library/fines" },
      { label: "Activity Logs", icon: History, href: "/library/transactions" },
      { label: "Reports Module", icon: FileText, href: "/library/reports" },
      { label: "Library Settings", icon: Settings, href: "/library/settings" },
    ],
  },
  transport: {
    role: "transport",
    roleLabel: "Transport Admin",
    items: [
      { label: "Fleet Dashboard", icon: LayoutDashboard, href: "/transport/dashboard" },
      { label: "Vehicle Register", icon: Bus, href: "/transport/vehicles" },
      { label: "Routes & Stoppages", icon: Building2, href: "/transport/routes" },
      { label: "Staff & Drivers", icon: Users, href: "/transport/drivers" },
      { label: "GPS Route Allocations", icon: UserCheck, href: "/transport/allocation" },
      { label: "Fuel Expenses", icon: CreditCard, href: "/transport/fuel" },
      { label: "Attendance Log", icon: ClipboardList, href: "/transport/attendance" },
      { label: "Trips History", icon: History, href: "/transport/trips" },
      { label: "General Settings", icon: Settings, href: "/transport/settings" },
    ],
  },
  hostel: {
    role: "hostel",
    roleLabel: "Hostel Warden",
    items: [
      { label: "Hostel Dashboard", icon: LayoutDashboard, href: "/hostel/dashboard" },
      { label: "Rooms & Beds Layout", icon: Home, href: "/hostel/rooms-beds" },
      { label: "Student Residents", icon: Users, href: "/hostel/students" },
      { label: "Allotment Desk", icon: ClipboardList, href: "/hostel/allocation" },
      { label: "Leave Log", icon: Calendar, href: "/hostel/leave" },
      { label: "Guest Logs", icon: UserCheck, href: "/hostel/visitors" },
      { label: "Complaints Register", icon: HelpCircle, href: "/hostel/complaints" },
      { label: "Billing & Fees", icon: CreditCard, href: "/hostel/finance" },
      { label: "Hostel Reports", icon: FileText, href: "/hostel/reports" },
      { label: "Warden Settings", icon: Settings, href: "/hostel/settings" },
    ],
  },
  teacher: {
    role: "teacher",
    roleLabel: "Educator",
    items: [
      { label: "My Dashboard", icon: LayoutDashboard, href: "/teacher/dashboard" },
      { label: "My Classes", icon: GraduationCap, href: "/teacher/my-classes" },
      { label: "Roll Call", icon: UserCheck, href: "/teacher/attendance" },
      { label: "Homework Desk", icon: ClipboardList, href: "/teacher/homework" },
      { label: "Exam Marks Entry", icon: FileCheck, href: "/teacher/examinations" },
      { label: "Class Timetable", icon: Calendar, href: "/teacher/timetable" },
      { label: "Notice Board", icon: FileText, href: "/teacher/notice-board" },
      { label: "Student Chats", icon: MessageSquare, href: "/teacher/messages" },
      { label: "Leave Requests", icon: CalendarRange, href: "/teacher/leave" },
      { label: "My Profile", icon: Users, href: "/teacher/profile" },
    ],
  },
  student: {
    role: "student",
    roleLabel: "Student",
    items: [
      { label: "My Portal", icon: LayoutDashboard, href: "/student/dashboard" },
      { label: "My Profile", icon: Users, href: "/student/profile" },
      { label: "Attendance Sheet", icon: UserCheck, href: "/student/attendance" },
      { label: "Timetable Schedule", icon: Calendar, href: "/student/timetable" },
      { label: "Assignments & Homework", icon: ClipboardList, href: "/student/homework" },
      { label: "My Exams", icon: FileCheck, href: "/student/examinations" },
      { label: "Results / Report Card", icon: FileText, href: "/student/results" },
      { label: "Fee Ledger", icon: CreditCard, href: "/student/fees" },
      { label: "Library Catalog", icon: BookOpen, href: "/student/library" },
      { label: "Bus Route Status", icon: Bus, href: "/student/transport" },
      { label: "Leave Application", icon: CalendarRange, href: "/student/leave" },
      { label: "Inbox Messages", icon: MessageSquare, href: "/student/messages" },
    ],
  },
  parent: {
    role: "parent",
    roleLabel: "Parent",
    items: [
      { label: "Dashboard", icon: LayoutDashboard, href: "/parent/dashboard" },
      { label: "My Children Profiles", icon: Users, href: "/parent/my-children" },
      { label: "Kids Attendance", icon: UserCheck, href: "/parent/attendance" },
      { label: "Fee Invoices", icon: CreditCard, href: "/parent/fees" },
      { label: "Class Timetables", icon: Calendar, href: "/parent/timetable" },
      { label: "Homework Status", icon: ClipboardList, href: "/parent/homework" },
      { label: "Grade Sheets", icon: FileText, href: "/parent/results" },
      { label: "School Notices", icon: FileText, href: "/parent/notices" },
      { label: "School Calendar", icon: CalendarRange, href: "/parent/calendar" },
      { label: "Teacher Messages", icon: MessageSquare, href: "/parent/messages" },
      { label: "Apply Leave", icon: Calendar, href: "/parent/leave" },
      { label: "Transport Info", icon: Bus, href: "/parent/transport" },
      { label: "Library Accounts", icon: BookOpen, href: "/parent/library" },
    ],
  },
};
