import {
  LayoutDashboard,
  Building2,
  Users,
  GraduationCap,
  CalendarRange,
  ClipboardList,
  FileCheck,
  Briefcase,
  CreditCard,
  BookOpen,
  Package,
  Bus,
  Home,
  HeartPulse,
  History,
  Settings,
  FileText,
  MessageSquare,
  Calendar,
  UserCheck,
  BadgePercent,
  CheckSquare,
  Shield,
  HelpCircle,
  Clock,
} from "lucide-react";
import { SidebarConfig } from "@/types/sidebar";

export const sidebarConfigs: Record<string, SidebarConfig> = {
  "super-admin": {
    role: "super-admin",
    roleLabel: "Super Admin",
    items: [
      {
        label: "Dashboard",
        icon: LayoutDashboard,
        children: [
          { label: "Overview", href: "/super-admin/dashboard" },
          { label: "Analytics", href: "/super-admin/dashboard/analytics" },
          { label: "Notifications", href: "/super-admin/dashboard/notifications" },
          { label: "Activities", href: "/super-admin/dashboard/activities" },
          { label: "Performance Reports", href: "/super-admin/dashboard/performance" },
        ],
      },
      {
        label: "Branch Management",
        icon: Building2,
        children: [
          { label: "All Branches", href: "/super-admin/branch-management" },
          { label: "Create Branch", href: "/super-admin/branch-management/create" },
          { label: "Branch Admins", href: "/super-admin/branch-management/admins" },
          { label: "Branch Settings", href: "/super-admin/branch-management/settings" },
          { label: "Performance Metrics", href: "/super-admin/branch-management/performance" },
          { label: "Branch Documents", href: "/super-admin/branch-management/documents" },
          { label: "Branch Fees", href: "/super-admin/branch-management/fees" },
          { label: "Branch Audit Logs", href: "/super-admin/branch-management/logs" },
          { label: "Branch Reports", href: "/super-admin/branch-management/reports" },
        ],
      },
      {
        label: "Admission CRM",
        icon: Users,
        children: [
          { label: "CRM Dashboard", href: "/super-admin/admission-crm" },
          { label: "Leads", href: "/super-admin/admission-crm/leads" },
          { label: "Inquiries List", href: "/super-admin/admission-crm/inquiries" },
          { label: "Follow Ups", href: "/super-admin/admission-crm/follow-ups" },
          { label: "Lead Sources", href: "/super-admin/admission-crm/sources" },
          { label: "Admission Pipeline", href: "/super-admin/admission-crm/leads" },
          { label: "Counselor Allocation", href: "/super-admin/admission-crm/counselors" },
          { label: "Admission Forms", href: "/super-admin/admission-crm/forms" },
          { label: "Documents", href: "/super-admin/admission-crm/documents" },
          { label: "Conversion Reports", href: "/super-admin/admission-crm/reports" },
          { label: "Rejected Leads", href: "/super-admin/admission-crm/rejected" },
          { label: "CRM Settings", href: "/super-admin/admission-crm/settings" },
        ],
      },
      {
        label: "Student Directory",
        icon: GraduationCap,
        children: [
          { label: "All Students", href: "/super-admin/students" },
          { label: "Add Student", href: "/super-admin/students/create" },
          { label: "Student Profile", href: "/super-admin/students/profile" },
          { label: "Student Transfer", href: "/super-admin/students/transfer" },
          { label: "Student Promotion", href: "/super-admin/students/promotion" },
          { label: "Student Passouts", href: "/super-admin/students/passouts" },
          { label: "Student Guard Details", href: "/super-admin/students/guardians" },
          { label: "Student Documents", href: "/super-admin/students/documents" },
          { label: "Student Categories", href: "/super-admin/students/categories" },
          { label: "ID Cards", href: "/super-admin/students/id-cards" },
          { label: "Certificates", href: "/super-admin/students/certificates" },
          { label: "Discipline Records", href: "/super-admin/students/discipline" },
          { label: "Achievements", href: "/super-admin/students/achievements" },
          { label: "Medical Records", href: "/super-admin/students/medical" },
          { label: "Alumni Directory", href: "/super-admin/students/alumni" },
          { label: "Student Reports", href: "/super-admin/students/reports" },
        ],
      },
      {
        label: "Academic Operations",
        icon: CalendarRange,
        children: [
          { label: "Class Management", href: "/super-admin/academic/classes" },
          { label: "Sections List", href: "/super-admin/academic/sections" },
          { label: "Subjects Catalog", href: "/super-admin/academic/subjects" },
          { label: "Teacher Allocation", href: "/super-admin/academic/teacher-allocation" },
          { label: "Timetable Master", href: "/super-admin/academic/timetable" },
          { label: "Academic Session", href: "/super-admin/academic/session" },
          { label: "Academic Calendar", href: "/super-admin/academic/calendar" },
          { label: "Lesson Plans", href: "/super-admin/academic/lessons" },
          { label: "Syllabus Manager", href: "/super-admin/academic/syllabus" },
          { label: "Assignments", href: "/super-admin/academic/assignments" },
          { label: "Projects", href: "/super-admin/academic/projects" },
          { label: "Curriculum Map", href: "/super-admin/academic/curriculum" },
          { label: "Class Reports", href: "/super-admin/academic/class-reports" },
          { label: "Subject Reports", href: "/super-admin/academic/subject-reports" },
          { label: "Academic Settings", href: "/super-admin/academic/settings" },
        ],
      },
      {
        label: "Attendance Manager",
        icon: UserCheck,
        children: [
          { label: "Daily Attendance", href: "/super-admin/attendance" },
          { label: "Student Attendance", href: "/super-admin/attendance/students" },
          { label: "Teacher Attendance", href: "/super-admin/attendance/teachers" },
          { label: "Staff Attendance", href: "/super-admin/attendance/staff" },
          { label: "Attendance Reports", href: "/super-admin/attendance/reports" },
          { label: "Monthly Reports", href: "/super-admin/attendance/monthly" },
          { label: "Holiday Calendar", href: "/super-admin/attendance/calendar" },
          { label: "Leave Requests", href: "/super-admin/attendance/leaves" },
          { label: "Leave Reports", href: "/super-admin/attendance/leave-reports" },
          { label: "Attendance Settings", href: "/super-admin/attendance/settings" },
        ],
      },
      {
        label: "Examinations & Grading",
        icon: FileCheck,
        children: [
          { label: "Exams Setup", href: "/super-admin/examinations" },
          { label: "Exam Types", href: "/super-admin/examinations/types" },
          { label: "Exam Schedule", href: "/super-admin/examinations/schedule" },
          { label: "Hall Allocation", href: "/super-admin/examinations/halls" },
          { label: "Marks Entry", href: "/super-admin/examinations/marks" },
          { label: "Grade Cards", href: "/super-admin/examinations/grades" },
          { label: "Results Processing", href: "/super-admin/examinations/results" },
          { label: "Report Cards", href: "/super-admin/examinations/report-cards" },
          { label: "Rankings", href: "/super-admin/examinations/rankings" },
          { label: "Result Analytics", href: "/super-admin/examinations/analytics" },
          { label: "Exam Reports", href: "/super-admin/examinations/reports" },
          { label: "Exam Settings", href: "/super-admin/examinations/settings" },
        ],
      },
      {
        label: "Staff & HR",
        icon: Briefcase,
        children: [
          { label: "Staff Directory", href: "/super-admin/staff-hr" },
          { label: "Add Employee", href: "/super-admin/staff-hr/create" },
          { label: "Departments", href: "/super-admin/staff-hr/departments" },
          { label: "Designations", href: "/super-admin/staff-hr/designations" },
          { label: "Recruitment Portal", href: "/super-admin/staff-hr/recruitment" },
          { label: "Candidates List", href: "/super-admin/staff-hr/candidates" },
          { label: "Interviews Schedule", href: "/super-admin/staff-hr/interviews" },
          { label: "Employee Documents", href: "/super-admin/staff-hr/documents" },
          { label: "Leave Management", href: "/super-admin/staff-hr/leave" },
          { label: "Attendance Logs", href: "/super-admin/staff-hr/attendance" },
          { label: "Performance Monitor", href: "/super-admin/staff-hr/performance" },
          { label: "Appraisals Panel", href: "/super-admin/staff-hr/appraisals" },
          { label: "Training & Development", href: "/super-admin/staff-hr/training" },
          { label: "Staff Reports", href: "/super-admin/staff-hr/reports" },
          { label: "HR Settings", href: "/super-admin/staff-hr/settings" },
        ],
      },
      {
        label: "Payroll Processing",
        icon: CheckSquare,
        children: [
          { label: "Salary Structure", href: "/super-admin/payroll/structure" },
          { label: "Process Payroll", href: "/super-admin/payroll/process" },
          { label: "Employee Payslips", href: "/super-admin/payroll/payslips" },
          { label: "Bonuses Ledger", href: "/super-admin/payroll/bonuses" },
          { label: "Deductions Ledger", href: "/super-admin/payroll/deductions" },
          { label: "Reimbursements", href: "/super-admin/payroll/reimbursements" },
          { label: "Tax Management", href: "/super-admin/payroll/tax" },
          { label: "Payroll Reports", href: "/super-admin/payroll/reports" },
          { label: "Salary Analytics", href: "/super-admin/payroll/analytics" },
          { label: "Payroll Settings", href: "/super-admin/payroll/settings" },
        ],
      },
      {
        label: "Fees & Accounts",
        icon: CreditCard,
        children: [
          { label: "Fee Structure", href: "/super-admin/fees-accounts/structure" },
          { label: "Fee Categories", href: "/super-admin/fees-accounts/categories" },
          { label: "Fee Collection", href: "/super-admin/fees-accounts/collection" },
          { label: "Receipts Log", href: "/super-admin/fees-accounts/receipts" },
          { label: "Pending Fees", href: "/super-admin/fees-accounts/pending" },
          { label: "Fee Discounts", href: "/super-admin/fees-accounts/discounts" },
          { label: "Scholarships Setup", href: "/super-admin/fees-accounts/scholarships" },
          { label: "Refunds Processing", href: "/super-admin/fees-accounts/refunds" },
          { label: "Expenses Entry", href: "/super-admin/fees-accounts/expenses" },
          { label: "Income Ledger", href: "/super-admin/fees-accounts/income" },
          { label: "Vendors Catalog", href: "/super-admin/fees-accounts/vendors" },
          { label: "Transactions Ledger", href: "/super-admin/fees-accounts/transactions" },
          { label: "Financial Reports", href: "/super-admin/fees-accounts/reports" },
          { label: "Profit & Loss Account", href: "/super-admin/fees-accounts/profit-loss" },
          { label: "Financial Settings", href: "/super-admin/fees-accounts/settings" },
        ],
      },
      {
        label: "Library Operations",
        icon: BookOpen,
        children: [
          { label: "Books Catalog", href: "/super-admin/library/books" },
          { label: "Book Categories", href: "/super-admin/library/categories" },
          { label: "Authors Directory", href: "/super-admin/library/authors" },
          { label: "Publishers Catalog", href: "/super-admin/library/publishers" },
          { label: "Issue Book", href: "/super-admin/library/issue-return" },
          { label: "Return Book", href: "/super-admin/library/issue-return" },
          { label: "Fine Tracker", href: "/super-admin/library/fines" },
          { label: "Book Requests", href: "/super-admin/library/requests" },
          { label: "Library Reports", href: "/super-admin/library/reports" },
          { label: "Library Settings", href: "/super-admin/library/settings" },
        ],
      },
      {
        label: "Inventory & Assets",
        icon: Package,
        children: [
          { label: "Products Catalog", href: "/super-admin/inventory/products" },
          { label: "Product Categories", href: "/super-admin/inventory/categories" },
          { label: "Stock Levels", href: "/super-admin/inventory/stock" },
          { label: "Purchase Orders", href: "/super-admin/inventory/purchase-orders" },
          { label: "Suppliers & Vendors", href: "/super-admin/inventory/vendors" },
          { label: "Assets Register", href: "/super-admin/inventory/assets" },
          { label: "Consumables Log", href: "/super-admin/inventory/consumables" },
          { label: "Inventory Reports", href: "/super-admin/inventory/reports" },
          { label: "Stock Alerts", href: "/super-admin/inventory/alerts" },
          { label: "Inventory Settings", href: "/super-admin/inventory/settings" },
        ],
      },
      {
        label: "Transport Management",
        icon: Bus,
        children: [
          { label: "Vehicles Fleet", href: "/super-admin/transport/vehicles" },
          { label: "Drivers Directory", href: "/super-admin/transport/drivers" },
          { label: "Routes & Stops", href: "/super-admin/transport/routes" },
          { label: "Stops Manager", href: "/super-admin/transport/stops" },
          { label: "GPS Real-time Tracking", href: "/super-admin/transport/gps" },
          { label: "Fuel Logbook", href: "/super-admin/transport/fuel" },
          { label: "Fleet Maintenance", href: "/super-admin/transport/maintenance" },
          { label: "Insurance Register", href: "/super-admin/transport/insurance" },
          { label: "Vehicle Documents", href: "/super-admin/transport/documents" },
          { label: "Assigned Schedules", href: "/super-admin/transport/assignments" },
          { label: "Transport Reports", href: "/super-admin/transport/reports" },
          { label: "Transport Settings", href: "/super-admin/transport/settings" },
        ],
      },
      {
        label: "Hostel Management",
        icon: Home,
        children: [
          { label: "Hostel Blocks", href: "/super-admin/hostel/blocks" },
          { label: "Rooms Status", href: "/super-admin/hostel/rooms" },
          { label: "Beds Status", href: "/super-admin/hostel/beds" },
          { label: "Bed Allocation", href: "/super-admin/hostel/allocation" },
          { label: "Room Transfer", href: "/super-admin/hostel/transfer" },
          { label: "Hostel Attendance", href: "/super-admin/hostel/attendance" },
          { label: "Hostel Fees", href: "/super-admin/hostel/fees" },
          { label: "Hostel Visitor Logs", href: "/super-admin/hostel/visitors" },
          { label: "Complaints Box", href: "/super-admin/hostel/complaints" },
          { label: "Mess Management", href: "/super-admin/hostel/mess" },
          { label: "Hostel Reports", href: "/super-admin/hostel/reports" },
          { label: "Hostel Settings", href: "/super-admin/hostel/settings" },
        ],
      },
      {
        label: "Health Center",
        icon: HeartPulse,
        children: [
          { label: "Medical Records", href: "/super-admin/health-center/records" },
          { label: "Medical Visits", href: "/super-admin/health-center/visits" },
          { label: "Vaccinations Log", href: "/super-admin/health-center/vaccinations" },
          { label: "Health Reports", href: "/super-admin/health-center/reports" },
          { label: "Emergency Contacts", href: "/super-admin/health-center/emergency" },
          { label: "Medicine Inventory", href: "/super-admin/health-center/medicine" },
          { label: "Doctor Visits", href: "/super-admin/health-center/doctor-visits" },
          { label: "Clinic Settings", href: "/super-admin/health-center/settings" },
        ],
      },
      {
        label: "Visitor Management",
        icon: Users,
        children: [
          { label: "Visitor Log", href: "/super-admin/visitor-management/visitors" },
          { label: "Complaints Box", href: "/super-admin/visitor-management/complaints" },
        ],
      },
      {
        label: "Reports & Analytics",
        icon: FileText,
        children: [
          { label: "Main Dashboard", href: "/super-admin/reports" },
          { label: "Student Reports", href: "/super-admin/reports/students" },
          { label: "Attendance Reports", href: "/super-admin/reports/attendance" },
          { label: "Fee Reports", href: "/super-admin/reports/fees" },
          { label: "Payroll Reports", href: "/super-admin/reports/payroll" },
          { label: "Library Reports", href: "/super-admin/reports/library" },
          { label: "Inventory Reports", href: "/super-admin/reports/inventory" },
          { label: "Transport Reports", href: "/super-admin/reports/transport" },
          { label: "Hostel Reports", href: "/super-admin/reports/hostel" },
          { label: "Admission Reports", href: "/super-admin/reports/admission" },
          { label: "Academic Reports", href: "/super-admin/reports/academic" },
          { label: "Financial Reports", href: "/super-admin/reports/financial" },
          { label: "Custom Export", href: "/super-admin/reports/export" },
          { label: "PDF Export Utility", href: "/super-admin/reports/pdf" },
          { label: "Excel Export Utility", href: "/super-admin/reports/excel" },
          { label: "Scheduled Reports", href: "/super-admin/reports/scheduled" },
        ],
      },
      {
        label: "System Logs",
        icon: History,
        children: [
          { label: "Audit Ledger", href: "/super-admin/audit-logs" },
          { label: "Login Logs", href: "/super-admin/audit-logs/login" },
          { label: "Session Activity", href: "/super-admin/audit-logs/activity" },
          { label: "System Service Logs", href: "/super-admin/audit-logs/system" },
          { label: "Security Logs", href: "/super-admin/audit-logs/security" },
          { label: "User Action Logs", href: "/super-admin/audit-logs/users" },
        ],
      },
      {
        label: "General Settings",
        icon: Settings,
        children: [
          { label: "School Profile", href: "/super-admin/settings" },
          { label: "Branch Settings", href: "/super-admin/settings/branches" },
          { label: "User Roles & Access", href: "/super-admin/settings/roles" },
          { label: "Security Permissions", href: "/super-admin/settings/permissions" },
          { label: "SMS Gateway Config", href: "/super-admin/settings/sms" },
          { label: "Email Gateway Config", href: "/super-admin/settings/email" },
          { label: "WhatsApp Broadcast Config", href: "/super-admin/settings/whatsapp" },
          { label: "Payment Gateway Integration", href: "/super-admin/settings/payment" },
          { label: "Theme Configurations", href: "/super-admin/settings/theme" },
          { label: "Logo & Asset Management", href: "/super-admin/settings/logo" },
          { label: "Notification Triggers", href: "/super-admin/settings/notifications" },
          { label: "Language Configurations", href: "/super-admin/settings/language" },
          { label: "Automated Backup Settings", href: "/super-admin/settings/backup" },
          { label: "System Restore Points", href: "/super-admin/settings/restore" },
          { label: "API Keys & Integrations", href: "/super-admin/settings/api-keys" },
          { label: "Security Access Audit", href: "/super-admin/settings/security-audit" },
          { label: "Session Management", href: "/super-admin/settings/sessions" },
          { label: "Database Cluster Settings", href: "/super-admin/settings/database" },
          { label: "System Configurations", href: "/super-admin/settings/system" },
        ],
      },
    ],
  },
  "branch-admin": {
    role: "branch-admin",
    roleLabel: "Branch Admin",
    items: [
      {
        label: "Dashboard",
        icon: LayoutDashboard,
        children: [
          { label: "Overview", href: "/branch-admin/dashboard" },
          { label: "Today's Summary", href: "/branch-admin/dashboard/summary" },
          { label: "Notifications", href: "/branch-admin/dashboard/notifications" },
          { label: "Pending Approvals", href: "/branch-admin/dashboard/pending-approvals" },
          { label: "Branch Analytics", href: "/branch-admin/dashboard/analytics" },
        ],
      },
      {
        label: "Students",
        icon: GraduationCap,
        children: [
          { label: "Student List", href: "/branch-admin/students" },
          { label: "Add Student", href: "/branch-admin/students/create" },
          { label: "Student Profiles", href: "/branch-admin/students/profiles" },
          { label: "Student Documents", href: "/branch-admin/students/documents" },
          { label: "Student Categories", href: "/branch-admin/students/categories" },
          { label: "Parent Details", href: "/branch-admin/students/guardians" },
          { label: "Student Transfer", href: "/branch-admin/students/transfers" },
          { label: "Student Promotion", href: "/branch-admin/students/promotions" },
          { label: "ID Cards", href: "/branch-admin/students/id-cards" },
          { label: "Certificates", href: "/branch-admin/students/certificates" },
          { label: "Medical Records", href: "/branch-admin/students/medical" },
          { label: "Discipline Records", href: "/branch-admin/students/discipline" },
          { label: "Achievements", href: "/branch-admin/students/achievements" },
          { label: "Bulk Import", href: "/branch-admin/students/bulk-import" },
          { label: "Student Reports", href: "/branch-admin/students/reports" },
        ],
      },
      {
        label: "Admission CRM",
        icon: Briefcase,
        children: [
          { label: "CRM Dashboard", href: "/branch-admin/admission-crm" },
          { label: "CRM Inquiries", href: "/branch-admin/admission-crm/inquiries" },
          { label: "CRM Leads", href: "/branch-admin/admission-crm/leads" },
          { label: "Follow-Ups", href: "/branch-admin/admission-crm/follow-ups" },
          { label: "Admission Forms", href: "/branch-admin/admission-crm/forms" },
          { label: "Lead Sources", href: "/branch-admin/admission-crm/sources" },
          { label: "Counselors", href: "/branch-admin/admission-crm/counselors" },
          { label: "Admission Pipeline", href: "/branch-admin/admission-crm/pipeline" },
          { label: "Document Verification", href: "/branch-admin/admission-crm/verification" },
          { label: "Admission Approval", href: "/branch-admin/admission-crm/approval" },
          { label: "Conversion Reports", href: "/branch-admin/admission-crm/reports" },
          { label: "CRM Settings", href: "/branch-admin/admission-crm/settings" },
        ],
      },
      {
        label: "Academic",
        icon: BookOpen,
        children: [
          { label: "Classes", href: "/branch-admin/classes-sections" },
          { label: "Sections", href: "/branch-admin/classes-sections" },
          { label: "Subjects", href: "/branch-admin/subjects" },
          { label: "Timetable", href: "/branch-admin/timetable" },
          { label: "Academic Calendar", href: "/branch-admin/academic-calendar" },
          { label: "Syllabus Monitor", href: "/branch-admin/syllabus" },
        ],
      },
      {
        label: "Attendance",
        icon: UserCheck,
        children: [
          { label: "Student Attendance", href: "/branch-admin/attendance" },
          { label: "Teacher Attendance", href: "/branch-admin/attendance/teacher" },
          { label: "Staff Attendance", href: "/branch-admin/attendance/staff" },
          { label: "Attendance Reports", href: "/branch-admin/attendance/reports" },
          { label: "Leave Requests", href: "/branch-admin/attendance/leaves" },
          { label: "Leave Reports", href: "/branch-admin/attendance/leave-reports" },
          { label: "Monthly Reports", href: "/branch-admin/attendance/monthly" },
          { label: "Holiday Calendar", href: "/branch-admin/attendance/holiday-calendar" },
          { label: "Attendance Settings", href: "/branch-admin/attendance/settings" },
        ],
      },
      {
        label: "Examination",
        icon: FileCheck,
        children: [
          { label: "Exam Setup", href: "/branch-admin/examinations" },
          { label: "Marks Entry", href: "/branch-admin/examinations" },
          { label: "Result Processing", href: "/branch-admin/examinations" },
          { label: "Report Cards", href: "/branch-admin/examinations" },
          { label: "Grades & GPA", href: "/branch-admin/examinations/grades" },
        ],
      },
      {
        label: "Staff Management",
        icon: Users,
        children: [
          { label: "Staff List", href: "/branch-admin/employees" },
          { label: "Departments", href: "/branch-admin/employees" },
          { label: "Leave Management", href: "/branch-admin/attendance/leaves" },
          { label: "Staff Documents", href: "/branch-admin/employees" },
          { label: "All Users", href: "/branch-admin/user-management" },
          { label: "Create User", href: "/branch-admin/user-management/create" },
          { label: "Role Management", href: "/branch-admin/user-management/roles" },
          { label: "Permissions", href: "/branch-admin/user-management/permissions" },
          { label: "Academic Users", href: "/branch-admin/user-management/academic" },
          { label: "Finance Users", href: "/branch-admin/user-management/finance" },
          { label: "HR Users", href: "/branch-admin/user-management/hr" },
          { label: "Library Users", href: "/branch-admin/user-management/library" },
          { label: "Transport Users", href: "/branch-admin/user-management/transport" },
          { label: "Hostel Users", href: "/branch-admin/user-management/hostel" },
          { label: "Teacher Users", href: "/branch-admin/user-management/teachers" },
          { label: "Login Activity Logs", href: "/branch-admin/user-management/logs" },
        ],
      },
      {
        label: "Fees",
        icon: CreditCard,
        children: [
          { label: "Fee Collection", href: "/branch-admin/fee-collection" },
          { label: "Fee Structure", href: "/branch-admin/fee-management" },
          { label: "Discounts & Approvals", href: "/branch-admin/approvals/discounts" },
          { label: "Due Management", href: "/branch-admin/due-management" },
          { label: "Scholarships", href: "/branch-admin/approvals/scholarships" },
          { label: "Admissions Approvals", href: "/branch-admin/approvals/admissions" },
          { label: "Transfers Approvals", href: "/branch-admin/approvals/transfers" },
          { label: "Expense Approvals", href: "/branch-admin/approvals/expenses" },
          { label: "Purchase Requests", href: "/branch-admin/approvals/purchase" },
          { label: "Staff Requests", href: "/branch-admin/approvals/staff" },
          { label: "Pending Summary", href: "/branch-admin/approvals/pending" },
        ],
      },
      {
        label: "Payroll",
        icon: ClipboardList,
        children: [
          { label: "Payroll Processing", href: "/branch-admin/payroll" },
          { label: "Payslips", href: "/branch-admin/payroll" },
          { label: "Salary Structure", href: "/branch-admin/payroll" },
          { label: "Payroll Reports", href: "/branch-admin/payroll" },
        ],
      },
      {
        label: "Library",
        icon: BookOpen,
        children: [
          { label: "Books Catalog", href: "/branch-admin/books" },
          { label: "Issue / Return", href: "/branch-admin/issue-return" },
          { label: "Fine Management", href: "/branch-admin/fines" },
          { label: "Library Reports", href: "/branch-admin/reports/library" },
        ],
      },
      {
        label: "Inventory",
        icon: Package,
        children: [
          { label: "Products & Assets", href: "/branch-admin/inventory/assets" },
          { label: "Product Categories", href: "/branch-admin/inventory/categories" },
          { label: "Stock Levels", href: "/branch-admin/inventory/stock" },
          { label: "Purchase Orders", href: "/branch-admin/inventory/purchase-orders" },
        ],
      },
      {
        label: "Transport",
        icon: Bus,
        children: [
          { label: "Vehicles Fleet", href: "/branch-admin/transport/vehicles" },
          { label: "Drivers Directory", href: "/branch-admin/transport/drivers" },
          { label: "Routes & Stops", href: "/branch-admin/transport/routes" },
          { label: "Fuel Logbook", href: "/branch-admin/transport/fuel" },
        ],
      },
      {
        label: "Hostel",
        icon: Home,
        children: [
          { label: "Hostel Blocks", href: "/branch-admin/hostel/blocks" },
          { label: "Rooms & Beds", href: "/branch-admin/hostel/rooms-beds" },
          { label: "Bed Allocation", href: "/branch-admin/hostel/allocation" },
        ],
      },
      {
        label: "Reports",
        icon: FileText,
        children: [
          { label: "Report Builder", href: "/branch-admin/reports" },
          { label: "Student Reports", href: "/branch-admin/reports/students" },
          { label: "Admission Reports", href: "/branch-admin/reports/admission" },
          { label: "Attendance Reports", href: "/branch-admin/reports/attendance" },
          { label: "Academic Reports", href: "/branch-admin/reports/academic" },
          { label: "Finance Reports", href: "/branch-admin/reports/finance" },
          { label: "Payroll Reports", href: "/branch-admin/reports/payroll" },
          { label: "Library Reports", href: "/branch-admin/reports/library" },
          { label: "Transport Reports", href: "/branch-admin/reports/transport" },
          { label: "Hostel Reports", href: "/branch-admin/reports/hostel" },
          { label: "HR Reports", href: "/branch-admin/reports/hr" },
          { label: "Custom Reports", href: "/branch-admin/reports/custom" },
          { label: "Analytics Dashboard", href: "/branch-admin/reports/analytics" },
          { label: "Daily Reports", href: "/branch-admin/reports/daily" },
          { label: "Monthly Reports", href: "/branch-admin/reports/monthly" },
          { label: "Yearly Reports", href: "/branch-admin/reports/yearly" },
          { label: "PDF Export Utility", href: "/branch-admin/reports/pdf" },
          { label: "Excel Export Utility", href: "/branch-admin/reports/excel" },
          { label: "Scheduled Reports", href: "/branch-admin/reports/scheduled" },
          { label: "Audit Reports", href: "/branch-admin/reports/audit" },
          { label: "Performance Reports", href: "/branch-admin/reports/performance" },
        ],
      },
      {
        label: "Communications",
        icon: MessageSquare,
        children: [
          { label: "Notice Board", href: "/branch-admin/communications" },
          { label: "SMS Broadcast", href: "/branch-admin/communications/sms" },
          { label: "Email Broadcast", href: "/branch-admin/communications/email" },
          { label: "WhatsApp Broadcast", href: "/branch-admin/communications/whatsapp" },
          { label: "Message Templates", href: "/branch-admin/communications/templates" },
          { label: "Push Notifications", href: "/branch-admin/communications/push" },
          { label: "Parent Messages", href: "/branch-admin/communications/parent" },
          { label: "Teacher Messages", href: "/branch-admin/communications/teacher" },
          { label: "Communication Logs", href: "/branch-admin/communications/logs" },
        ],
      },
      {
        label: "Settings",
        icon: Settings,
        children: [
          { label: "Profile Settings", href: "/branch-admin/settings" },
          { label: "Academic Settings", href: "/branch-admin/settings/academic" },
          { label: "Admission Settings", href: "/branch-admin/settings/admission" },
          { label: "Fee Settings", href: "/branch-admin/settings/fee" },
          { label: "Attendance Settings", href: "/branch-admin/settings/attendance" },
          { label: "Communication Settings", href: "/branch-admin/settings/communication" },
          { label: "Logo Configuration", href: "/branch-admin/settings/logo" },
          { label: "Theme Configuration", href: "/branch-admin/settings/theme" },
          { label: "Session Management", href: "/branch-admin/settings/sessions" },
          { label: "Password Policy", href: "/branch-admin/settings/password-policy" },
          { label: "Backup Configurations", href: "/branch-admin/settings/backup" },
          { label: "Restore Configurations", href: "/branch-admin/settings/restore" },
          { label: "Security Configurations", href: "/branch-admin/settings/security" },
          { label: "Third-party Integrations", href: "/branch-admin/settings/integrations" },
          { label: "General Settings", href: "/branch-admin/settings/general" },
        ],
      },
    ],
  },
  academic: {
    role: "academic",
    roleLabel: "Academic Head",
    items: [
      {
        label: "Dashboard",
        icon: LayoutDashboard,
        children: [
          { label: "Overview", href: "/academic/dashboard" },
          { label: "Academic Analytics", href: "/academic/dashboard/analytics" },
          { label: "Attendance Analytics", href: "/academic/dashboard/attendance-analytics" },
          { label: "Exam Analytics", href: "/academic/dashboard/exam-analytics" },
          { label: "Notifications", href: "/academic/dashboard/notifications" },
        ],
      },
      {
        label: "Classes & Sections",
        icon: Building2,
        children: [
          { label: "All Classes", href: "/academic/classes-sections" },
          { label: "Create Class", href: "/academic/classes-sections/create" },
          { label: "Sections List", href: "/academic/classes-sections/sections" },
          { label: "Assign Class Teacher", href: "/academic/classes-sections/assign-teacher" },
          { label: "Class Capacity", href: "/academic/classes-sections/capacity" },
          { label: "Class Overview", href: "/academic/classes-sections/overview" },
          { label: "Class Reports", href: "/academic/classes-sections/reports" },
        ],
      },
      {
        label: "Subjects",
        icon: BookOpen,
        children: [
          { label: "All Subjects", href: "/academic/subjects" },
          { label: "Create Subject", href: "/academic/subjects/create" },
          { label: "Subject Allocation", href: "/academic/subjects/allocations" },
          { label: "Subject Mapping", href: "/academic/subjects/mapping" },
          { label: "Subject Teachers", href: "/academic/subjects/teachers" },
          { label: "Subject Credits", href: "/academic/subjects/credits" },
          { label: "Subject Reports", href: "/academic/subjects/reports" },
          { label: "Subject Settings", href: "/academic/subjects/settings" },
        ],
      },
      {
        label: "Timetable",
        icon: CalendarRange,
        children: [
          { label: "Master Timetable", href: "/academic/timetable" },
          { label: "Class Timetable", href: "/academic/timetable/class" },
          { label: "Teacher Timetable", href: "/academic/timetable/teacher" },
          { label: "Room Allocation", href: "/academic/timetable/rooms" },
          { label: "Period Management", href: "/academic/timetable/periods" },
          { label: "Substitute Teacher", href: "/academic/timetable/substitutes" },
          { label: "Exam Timetable", href: "/academic/timetable/exams" },
          { label: "Timetable Generator", href: "/academic/timetable/generator" },
          { label: "Timetable Reports", href: "/academic/timetable/reports" },
        ],
      },
      {
        label: "Academic Calendar",
        icon: Calendar,
        children: [
          { label: "Academic Session", href: "/academic/academic-calendar" },
          { label: "School Events", href: "/academic/academic-calendar/events" },
          { label: "Holidays", href: "/academic/academic-calendar/holidays" },
          { label: "Exam Calendar", href: "/academic/academic-calendar/exams" },
          { label: "PTM Schedule", href: "/academic/academic-calendar/ptm" },
          { label: "Special Events", href: "/academic/academic-calendar/special" },
          { label: "Calendar Reports", href: "/academic/academic-calendar/reports" },
        ],
      },
      {
        label: "Syllabus Management",
        icon: ClipboardList,
        children: [
          { label: "Upload Syllabus", href: "/academic/syllabus" },
          { label: "Subject Syllabus", href: "/academic/syllabus/subject" },
          { label: "Chapter Management", href: "/academic/syllabus/chapters" },
          { label: "Lesson Planning", href: "/academic/syllabus/lessons" },
          { label: "Completion Tracking", href: "/academic/syllabus/tracking" },
          { label: "Teacher Progress", href: "/academic/syllabus/teachers" },
          { label: "Class Progress", href: "/academic/syllabus/classes" },
          { label: "Subject Progress", href: "/academic/syllabus/subjects" },
          { label: "Syllabus Reports", href: "/academic/syllabus/reports" },
        ],
      },
      {
        label: "Attendance Monitoring",
        icon: UserCheck,
        children: [
          { label: "Student Attendance", href: "/academic/attendance" },
          { label: "Class Attendance", href: "/academic/attendance/class" },
          { label: "Subject Attendance", href: "/academic/attendance/subject" },
          { label: "Teacher Attendance", href: "/academic/attendance/teacher" },
          { label: "Attendance Analytics", href: "/academic/attendance/analytics" },
          { label: "Attendance Reports", href: "/academic/attendance/reports" },
          { label: "Defaulters List", href: "/academic/attendance/defaulters" },
          { label: "Attendance Trends", href: "/academic/attendance/trends" },
          { label: "Monthly Reports", href: "/academic/attendance/monthly" },
        ],
      },
      {
        label: "Examinations",
        icon: FileCheck,
        children: [
          { label: "Exam Setup", href: "/academic/examinations" },
          { label: "Exam Types", href: "/academic/examinations/types" },
          { label: "Exam Schedule", href: "/academic/examinations/schedule" },
          { label: "Exam Centers", href: "/academic/examinations/centers" },
          { label: "Hall Allocation", href: "/academic/examinations/halls" },
          { label: "Invigilator Assignment", href: "/academic/examinations/invigilators" },
          { label: "Question Bank", href: "/academic/examinations/questions" },
          { label: "Exam Instructions", href: "/academic/examinations/instructions" },
          { label: "Marks Entry", href: "/academic/examinations/marks" },
          { label: "Practical Exams", href: "/academic/examinations/practical" },
          { label: "Exam Analytics", href: "/academic/examinations/analytics" },
          { label: "Grade System", href: "/academic/examinations/grades" },
          { label: "Exam Reports", href: "/academic/examinations/reports" },
          { label: "Result Processing", href: "/academic/examinations/results" },
        ],
      },
      {
        label: "Result Monitoring",
        icon: CheckSquare,
        children: [
          { label: "Result Verification", href: "/academic/results" },
          { label: "Publish Results", href: "/academic/results/publish" },
          { label: "Class Results", href: "/academic/results/classes" },
          { label: "Student Results", href: "/academic/results/students" },
          { label: "Subject Results", href: "/academic/results/subjects" },
          { label: "Rank Lists", href: "/academic/results/ranks" },
          { label: "Top Performers", href: "/academic/results/top" },
          { label: "Fail Analysis", href: "/academic/results/failures" },
          { label: "Grade Analysis", href: "/academic/results/grades" },
          { label: "Result Analytics", href: "/academic/results/analytics" },
          { label: "Report Cards", href: "/academic/results/report-cards" },
        ],
      },
      {
        label: "Teachers",
        icon: Users,
        children: [
          { label: "Teacher Directory", href: "/academic/teachers" },
          { label: "Teacher Allocation", href: "/academic/teachers/allocations" },
          { label: "Teacher Workload", href: "/academic/teachers/workloads" },
          { label: "Teacher Timetable", href: "/academic/teachers/timetable" },
          { label: "Teacher Attendance", href: "/academic/teachers/attendance" },
          { label: "Teacher Performance", href: "/academic/teachers/performance" },
          { label: "Observations Logs", href: "/academic/teachers/observations" },
          { label: "Training Programs", href: "/academic/teachers/training" },
          { label: "Appraisals Panel", href: "/academic/teachers/appraisals" },
          { label: "Teacher Reports", href: "/academic/teachers/reports" },
          { label: "Teacher Documents", href: "/academic/teachers/documents" },
        ],
      },
      {
        label: "Students Performance",
        icon: GraduationCap,
        children: [
          { label: "Student Performance", href: "/academic/students-performance" },
          { label: "Class Performance", href: "/academic/students-performance/classes" },
          { label: "Subject Performance", href: "/academic/students-performance/subjects" },
          { label: "Student Ranking", href: "/academic/students-performance/ranks" },
          { label: "Progress Tracking", href: "/academic/students-performance/progress" },
          { label: "Weak Students", href: "/academic/students-performance/weak" },
          { label: "Top Performers", href: "/academic/students-performance/top" },
          { label: "Performance Analytics", href: "/academic/students-performance/analytics" },
          { label: "Report Cards Print", href: "/academic/students-performance/report-cards" },
          { label: "Student Comparisons", href: "/academic/students-performance/comparisons" },
          { label: "Improvement Plans", href: "/academic/students-performance/improvements" },
        ],
      },
      {
        label: "Reports",
        icon: FileText,
        children: [
          { label: "Academic Reports", href: "/academic/reports" },
          { label: "Attendance Reports", href: "/academic/reports/attendance" },
          { label: "Exam Reports", href: "/academic/reports/exams" },
          { label: "Result Reports", href: "/academic/reports/results" },
          { label: "Teacher Reports", href: "/academic/reports/teachers" },
          { label: "Class Reports", href: "/academic/reports/classes" },
          { label: "Subject Reports", href: "/academic/reports/subjects" },
          { label: "Performance Reports", href: "/academic/reports/performance" },
          { label: "Defaulter Reports", href: "/academic/reports/defaulters" },
          { label: "Promotion Reports", href: "/academic/reports/promotions" },
          { label: "PDF Export Utility", href: "/academic/reports/pdf" },
          { label: "Excel Export Utility", href: "/academic/reports/excel" },
          { label: "Custom Reports", href: "/academic/reports/custom" },
          { label: "Scheduled Reports", href: "/academic/reports/scheduled" },
          { label: "Analytics Reports", href: "/academic/reports/analytics" },
        ],
      },
      {
        label: "Communications",
        icon: MessageSquare,
        children: [
          { label: "Notice Board", href: "/academic/communications" },
          { label: "Teacher Messages", href: "/academic/communications/teacher" },
          { label: "Student Messages", href: "/academic/communications/student" },
          { label: "Parent Messages", href: "/academic/communications/parent" },
          { label: "SMS Broadcasts", href: "/academic/communications/sms" },
          { label: "Email Broadcasts", href: "/academic/communications/email" },
        ],
      },
      {
        label: "Settings",
        icon: Settings,
        children: [
          { label: "Academic Settings", href: "/academic/settings" },
          { label: "Exam Settings", href: "/academic/settings/exams" },
          { label: "Attendance Settings", href: "/academic/settings/attendance" },
          { label: "Result Settings", href: "/academic/settings/results" },
          { label: "Promotion Rules", href: "/academic/settings/promotion" },
          { label: "Grade Settings", href: "/academic/settings/grading" },
          { label: "Session Settings", href: "/academic/settings/sessions" },
          { label: "Subject Settings", href: "/academic/settings/subjects" },
          { label: "Calendar Settings", href: "/academic/settings/calendar" },
          { label: "General Settings", href: "/academic/settings/general" },
        ],
      },
    ],
  },
  finance: {
    role: "finance",
    roleLabel: "Finance Manager",
    items: [
      { label: "Dashboard", icon: LayoutDashboard, href: "/finance/dashboard" },
      {
        label: "Fee Management",
        icon: CreditCard,
        children: [
          { label: "Fees Overview", href: "/finance/fee-management" },
          { label: "Fee Structure", href: "/finance/fee-management/structure" },
          { label: "Fee Categories", href: "/finance/fee-management/categories" },
          { label: "Late Fee Rules", href: "/finance/fee-management/rules" },
        ],
      },
      { label: "Fee Collection", icon: CreditCard, href: "/finance/fee-collection" },
      { label: "Receipts", icon: FileText, href: "/finance/receipts" },
      { label: "Due Management", icon: Clock, href: "/finance/due-management" },
      { label: "Refunds", icon: History, href: "/finance/refunds" },
      {
        label: "Expenses",
        icon: Briefcase,
        children: [
          { label: "Expense Entry", href: "/finance/expenses" },
          { label: "Expense Categories", href: "/finance/expenses/categories" },
          { label: "Expense Reports", href: "/finance/expenses/reports" },
        ],
      },
      { label: "Income", icon: BadgePercent, href: "/finance/income" },
      {
        label: "Salary & Payroll",
        icon: ClipboardList,
        children: [
          { label: "Salary Structure", href: "/finance/salary-payroll" },
          { label: "Payroll Processing", href: "/finance/salary-payroll/process" },
          { label: "Payslips Ledger", href: "/finance/salary-payroll/payslips" },
        ],
      },
      { label: "Scholarships & Discounts", icon: GraduationCap, href: "/finance/scholarships" },
      { label: "Bank & Accounts", icon: Building2, href: "/finance/bank-accounts" },
      {
        label: "Reports",
        icon: FileText,
        children: [
          { label: "Fee Reports", href: "/finance/reports/fees" },
          { label: "Expense Reports", href: "/finance/reports/expenses" },
          { label: "Income Reports", href: "/finance/reports/income" },
          { label: "Payroll Reports", href: "/finance/reports/payroll" },
          { label: "Bank Reports", href: "/finance/reports/bank" },
        ],
      },
      { label: "Financial Analytics", icon: LayoutDashboard, href: "/finance/reports" },
      { label: "Approvals", icon: Shield, href: "/finance/approvals" },
      { label: "Settings", icon: Settings, href: "/finance/settings" },
    ],
  },
  hr: {
    role: "hr",
    roleLabel: "HR Manager",
    items: [
      { label: "Dashboard", icon: LayoutDashboard, href: "/hr/dashboard" },
      {
        label: "Employees",
        icon: Users,
        children: [
          { label: "Employee List", href: "/hr/employees" },
          { label: "Add Employee", href: "/hr/employees/create" },
          { label: "Departments", href: "/hr/employees/departments" },
          { label: "Designations", href: "/hr/employees/designations" },
        ],
      },
      { label: "Attendance", icon: UserCheck, href: "/hr/attendance" },
      { label: "Leave Management", icon: Calendar, href: "/hr/leave" },
      { label: "Payroll", icon: CreditCard, href: "/hr/payroll" },
      { label: "Recruitment", icon: Briefcase, href: "/hr/recruitment" },
      { label: "Performance", icon: CheckSquare, href: "/hr/performance" },
      { label: "Training & Development", icon: GraduationCap, href: "/hr/training" },
      { label: "Documents", icon: FileText, href: "/hr/documents" },
      { label: "Policies", icon: FileText, href: "/hr/policies" },
      { label: "Assets", icon: Package, href: "/hr/assets" },
      { label: "Reports", icon: FileText, href: "/hr/reports" },
      { label: "Directory", icon: Users, href: "/hr/directory" },
      { label: "Settings", icon: Settings, href: "/hr/settings" },
    ],
  },
  library: {
    role: "library",
    roleLabel: "Librarian",
    items: [
      { label: "Dashboard", icon: LayoutDashboard, href: "/library/dashboard" },
      {
        label: "Book Management",
        icon: BookOpen,
        children: [
          { label: "All Books", href: "/library/books" },
          { label: "Add Book", href: "/library/books/create" },
          { label: "Categories", href: "/library/books/categories" },
          { label: "Publishers", href: "/library/books/publishers" },
        ],
      },
      {
        label: "Issue / Return",
        icon: ClipboardList,
        children: [
          { label: "Issue Book", href: "/library/issue-return/issue" },
          { label: "Return Book", href: "/library/issue-return/return" },
          { label: "Renew Book", href: "/library/issue-return/renew" },
        ],
      },
      {
        label: "Members",
        icon: Users,
        children: [
          { label: "All Members", href: "/library/members" },
          { label: "Add Member", href: "/library/members/create" },
        ],
      },
      { label: "Fine Management", icon: CreditCard, href: "/library/fines" },
      { label: "Library Transactions", icon: History, href: "/library/transactions" },
      { label: "Reports", icon: FileText, href: "/library/reports" },
      { label: "Settings", icon: Settings, href: "/library/settings" },
    ],
  },
  transport: {
    role: "transport",
    roleLabel: "Transport Manager",
    items: [
      { label: "Dashboard", icon: LayoutDashboard, href: "/transport/dashboard" },
      {
        label: "Vehicle Management",
        icon: Bus,
        children: [
          { label: "All Vehicles", href: "/transport/vehicles" },
          { label: "Add Vehicle", href: "/transport/vehicles/create" },
          { label: "Vehicle Documents", href: "/transport/vehicles/documents" },
          { label: "Vehicle Maintenance", href: "/transport/vehicles/maintenance" },
        ],
      },
      {
        label: "Route Management",
        icon: Building2,
        children: [
          { label: "All Routes", href: "/transport/routes" },
          { label: "Add Route", href: "/transport/routes/create" },
          { label: "Stops / Points", href: "/transport/routes/stops" },
        ],
      },
      {
        label: "Driver Management",
        icon: Users,
        children: [
          { label: "All Drivers", href: "/transport/drivers" },
          { label: "Add Driver", href: "/transport/drivers/create" },
          { label: "Driver Documents", href: "/transport/drivers/documents" },
        ],
      },
      { label: "Transport Allocation", icon: UserCheck, href: "/transport/allocation" },
      { label: "Fuel Management", icon: CreditCard, href: "/transport/fuel" },
      { label: "Attendance (Driver/Helper)", icon: ClipboardList, href: "/transport/attendance" },
      { label: "Trip Management", icon: History, href: "/transport/trips" },
      { label: "Reports", icon: FileText, href: "/transport/reports" },
      { label: "Settings", icon: Settings, href: "/transport/settings" },
    ],
  },
  hostel: {
    role: "hostel",
    roleLabel: "Hostel Warden",
    items: [
      { label: "Dashboard", icon: LayoutDashboard, href: "/hostel/dashboard" },
      { label: "Rooms & Beds", icon: Home, href: "/hostel/rooms-beds" },
      { label: "Hostel Students", icon: Users, href: "/hostel/students" },
      { label: "Room Allocation", icon: ClipboardList, href: "/hostel/allocation" },
      { label: "Leave Management", icon: Calendar, href: "/hostel/leave" },
      { label: "Visitors Management", icon: UserCheck, href: "/hostel/visitors" },
      { label: "Complaints", icon: HelpCircle, href: "/hostel/complaints" },
      { label: "Hostel Fee", icon: CreditCard, href: "/hostel/finance" },
      { label: "Payments", icon: CreditCard, href: "/hostel/finance/payments" },
      { label: "Occupancy Report", icon: FileText, href: "/hostel/reports/occupancy" },
      { label: "Fee Report", icon: FileText, href: "/hostel/reports/fees" },
      { label: "Leave Report", icon: FileText, href: "/hostel/reports/leave" },
      { label: "Visitor Report", icon: FileText, href: "/hostel/reports/visitors" },
      { label: "Hostel Settings", icon: Settings, href: "/hostel/settings" },
    ],
  },
  teacher: {
    role: "teacher",
    roleLabel: "Mathematics Teacher",
    items: [
      { label: "Dashboard", icon: LayoutDashboard, href: "/teacher/dashboard" },
      { label: "My Classes", icon: GraduationCap, href: "/teacher/my-classes" },
      { label: "Attendance", icon: UserCheck, href: "/teacher/attendance" },
      { label: "Homework", icon: ClipboardList, href: "/teacher/homework" },
      { label: "Examinations", icon: FileCheck, href: "/teacher/examinations" },
      { label: "Students", icon: Users, href: "/teacher/students" },
      { label: "Timetable", icon: Calendar, href: "/teacher/timetable" },
      { label: "Notice Board", icon: FileText, href: "/teacher/notice-board" },
      { label: "Messages", icon: MessageSquare, href: "/teacher/messages" },
      { label: "Leave Application", icon: CalendarRange, href: "/teacher/leave" },
      {
        label: "Reports",
        icon: FileText,
        children: [
          { label: "Student Progress", href: "/teacher/reports/progress" },
          { label: "Attendance Report", href: "/teacher/reports/attendance" },
        ],
      },
      { label: "My Profile", icon: Users, href: "/teacher/profile" },
      { label: "Settings", icon: Settings, href: "/teacher/settings" },
    ],
  },
  student: {
    role: "student",
    roleLabel: "Aditya Verma (Class 10-B)",
    items: [
      { label: "Dashboard", icon: LayoutDashboard, href: "/student/dashboard" },
      { label: "Profile", icon: Users, href: "/student/profile" },
      { label: "Attendance", icon: UserCheck, href: "/student/attendance" },
      { label: "Timetable", icon: Calendar, href: "/student/timetable" },
      { label: "Homework", icon: ClipboardList, href: "/student/homework" },
      { label: "Examinations", icon: FileCheck, href: "/student/examinations" },
      { label: "Results", icon: FileText, href: "/student/results" },
      { label: "Fees", icon: CreditCard, href: "/student/fees" },
      { label: "Library", icon: BookOpen, href: "/student/library" },
      { label: "Transport", icon: Bus, href: "/student/transport" },
      { label: "Downloads", icon: FileText, href: "/student/downloads" },
      { label: "Leave Application", icon: CalendarRange, href: "/student/leave" },
      { label: "Messages", icon: MessageSquare, href: "/student/messages" },
      { label: "Notices", icon: FileText, href: "/student/notices" },
      { label: "Settings", icon: Settings, href: "/student/settings" },
    ],
  },
  parent: {
    role: "parent",
    roleLabel: "Rajesh Verma (2 Children)",
    items: [
      { label: "Dashboard", icon: LayoutDashboard, href: "/parent/dashboard" },
      { label: "My Children", icon: Users, href: "/parent/children" },
      { label: "Attendance", icon: UserCheck, href: "/parent/attendance" },
      { label: "Fees & Payments", icon: CreditCard, href: "/parent/fees" },
      { label: "Timetable", icon: Calendar, href: "/parent/timetable" },
      { label: "Homework", icon: ClipboardList, href: "/parent/homework" },
      { label: "Examinations", icon: FileCheck, href: "/parent/examinations" },
      { label: "Results", icon: FileText, href: "/parent/results" },
      { label: "Notices", icon: FileText, href: "/parent/notices" },
      { label: "School Calendar", icon: CalendarRange, href: "/parent/calendar" },
      { label: "Messages", icon: MessageSquare, href: "/parent/messages" },
      { label: "Leave Application", icon: CalendarRange, href: "/parent/leave" },
      { label: "Transport", icon: Bus, href: "/parent/transport" },
      { label: "Library", icon: BookOpen, href: "/parent/library" },
      { label: "Profile Settings", icon: Settings, href: "/parent/settings" },
    ],
  },
};
